package com.ruoyi.portal;
import com.ruoyi.portal.PortalModels.*;
import com.ruoyi.portal.PortalEventModels.*;
import com.ruoyi.portal.PortalEventModels.Detail;
import com.ruoyi.helmet.pojo.po.RealTimeAlarm;
import com.ruoyi.common.core.domain.model.LoginUser;
import org.junit.jupiter.api.*;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

class PortalEventTest {
    PortalSource context;PortalEventSource source;PortalEventService service;MockMvc mvc;
    final List<String> routes=Arrays.asList("","/summary","/e","/e/timeline","/e/verifications");
    @BeforeEach void setup(){login("*:*:*");context=mock(PortalSource.class);source=mock(PortalEventSource.class);Context c=new Context();Site site=new Site();site.siteId="s";site.name="隔离厂站";c.sites.add(site);when(context.context(anyString())).thenReturn(c);when(source.visible(anyString(),eq("s"),anyString(),anyString(),anyString())).thenAnswer(i->!"hidden".equals(i.getArgument(3)));when(source.filters(anyString(),anyString())).thenAnswer(i->filters());when(source.events(anyString(),anyString())).thenAnswer(i->Section.available(new ArrayList<>(Arrays.asList(fact("e")))));when(source.statistics(anyString(),any())).thenAnswer(i->Section.missing("STATISTICS_NOT_INTEGRATED"));when(source.detail(anyString(),eq("s"),eq("e"))).thenAnswer(i->detail());when(source.timeline(anyString(),anyString(),anyString())).thenAnswer(i->Section.available(new ArrayList<>()));when(source.verifications(anyString(),anyString(),anyString())).thenAnswer(i->Section.available(new ArrayList<>()));service=new PortalEventService(new PortalAccess(),context,source);mvc=MockMvcBuilders.standaloneSetup(new PortalEventController(service)).setControllerAdvice(new PortalExceptionHandler()).build();}
    @AfterEach void clean(){SecurityContextHolder.clearContext();}
    void login(String...permissions){LoginUser u=new LoginUser();u.setUserId(101L);u.setPermissions(new HashSet<>(Arrays.asList(permissions)));SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(u,null,Collections.emptyList()));}
    PortalEventQuery q(){PortalEventQuery q=new PortalEventQuery();q.siteId="s";return q;}
    Filters filters(){Filters f=new Filters();f.keyword=f.timeRange=f.phase=true;Option o=new Option();o.value="TEST";o.label="合成类型";f.eventTypes=Section.available(Arrays.asList(o));return f;}
    Fact fact(String id){Fact f=new Fact();f.eventId=id;f.eventCode=id;f.siteId="s";f.title="隔离事件";f.sourceSystem="TEST";f.sourceEventId=id;f.deviceId="d";f.deviceCode="TEST-D";f.eventType="TEST";return f;}
    Detail detail(){Detail d=new Detail();d.event=fact("e");return d;}
    Ref ref(String id){Ref r=new Ref();r.id=id;r.siteId="s";r.name="隔离关联";r.attribution="CONFIRMED";r.evidenceId="proof";return r;}
    Verification verification(String id){Verification v=new Verification();v.id=id;v.siteId="s";v.eventId="e";v.state=VerificationState.DRAFT;return v;}
    Evidence evidence(String id){Evidence e=new Evidence();e.id=id;e.siteId="s";e.name="合成证据";e.attribution="CONFIRMED";e.evidenceId="proof";return e;}
    @Test void allFiveRequireLogin()throws Exception{SecurityContextHolder.clearContext();for(String p:routes)mvc.perform(get("/api/portal/v1/events"+p).param("siteId","s")).andExpect(status().isUnauthorized());verifyNoInteractions(source,context);}
    @Test void allFiveRequireEventPermission()throws Exception{login("portal:person:read");for(String p:routes)mvc.perform(get("/api/portal/v1/events"+p).param("siteId","s")).andExpect(status().isForbidden());verifyNoInteractions(source);}
    @Test void verificationHasAdditionalPermission()throws Exception{login("portal:event:read");mvc.perform(get("/api/portal/v1/events/e/verifications").param("siteId","s")).andExpect(status().isForbidden());mvc.perform(get("/api/portal/v1/events/e/timeline").param("siteId","s")).andExpect(status().isOk());}
    @Test void crossSiteAllDenied()throws Exception{for(String p:routes)mvc.perform(get("/api/portal/v1/events"+p).param("siteId","other")).andExpect(status().isForbidden());verifyNoInteractions(source);}
    @Test void invisibleDetailAndSubresources404()throws Exception{for(String p:Arrays.asList("/hidden","/hidden/timeline","/hidden/verifications"))mvc.perform(get("/api/portal/v1/events"+p).param("siteId","s")).andExpect(status().isNotFound());mvc.perform(get("/api/portal/v1/events/missing").param("siteId","s")).andExpect(status().isNotFound());}
    @Test void allFiveHaveReadEnvelope()throws Exception{for(String p:routes)mvc.perform(get("/api/portal/v1/events"+p).param("siteId","s")).andExpect(status().isOk()).andExpect(jsonPath("$.requestId").isString());}
    @Test void strictQuery()throws Exception{for(String n:Arrays.asList("0","101","bad"))mvc.perform(get("/api/portal/v1/events").param("siteId","s").param("pageSize",n)).andExpect(status().isBadRequest());mvc.perform(get("/api/portal/v1/events").param("siteId","s","other")).andExpect(status().isBadRequest());mvc.perform(get("/api/portal/v1/events/e").param("siteId","s").param("url","bad")).andExpect(status().isBadRequest());mvc.perform(get("/api/portal/v1/events").param("siteId","s").param("phase","DONE")).andExpect(status().isBadRequest());mvc.perform(get("/api/portal/v1/events/summary").param("siteId","s").param("pageNum","2")).andExpect(status().isBadRequest());}
    @Test void invalidTimeRange()throws Exception{for(String to:Arrays.asList("bad","2026-09-01T00:00:00Z","2026-08-01T00:00:00Z"))mvc.perform(get("/api/portal/v1/events").param("siteId","s").param("from","2026-09-01T00:00:00Z").param("to",to)).andExpect(status().isBadRequest());}
    @Test void unsupportedFiltersExplicit()throws Exception{when(source.filters(anyString(),anyString())).thenReturn(new Filters());for(String key:Arrays.asList("keyword","phase","eventType"))mvc.perform(get("/api/portal/v1/events").param("siteId","s").param(key,key.equals("phase")?"UNKNOWN":"TEST")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.errorCode").value("FILTER_NOT_SUPPORTED"));}
    @Test void filterBeforePageAndCount(){Fact a=fact("a"),b=fact("b");a.phase=Phase.PROCESSING;when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(a,b,fact("hidden"))));PortalEventQuery q=q();q.phase=Phase.PROCESSING;q.pageSize=1;q.pageNum=2;EventPage p=service.list(q);assertEquals(1L,p.total);assertTrue(p.items.isEmpty());}
    @Test void endTimeExclusiveAndUnknownExcluded(){Fact a=fact("a"),b=fact("b");a.occurredAt="2026-09-01T00:00:00Z";b.occurredAt="2026-09-02T00:00:00Z";when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(a,b,fact("c"))));PortalEventQuery q=q();q.from=a.occurredAt;q.to=b.occurredAt;assertEquals(1L,service.list(q).total);}
    @Test void mixedPrecisionTimesSortChronologically(){Fact a=fact("a"),b=fact("b");a.occurredAt="2026-09-01T00:00:00Z";b.occurredAt="2026-09-01T00:00:00.100Z";when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(a,b)));assertEquals("b",service.list(q()).items.get(0).eventId);Verification v=verification("v"),w=verification("w");v.sourceTime=a.occurredAt;w.sourceTime=b.occurredAt;when(source.verifications(anyString(),anyString(),anyString())).thenReturn(Section.available(Arrays.asList(v,w)));assertEquals("w",service.verifications(q(),"e").items.get(0).id);}
    @Test void noSourceNotZero(){when(source.events(anyString(),anyString())).thenReturn(Section.missing("EVENT_NOT_INTEGRATED"));assertNull(service.list(q()).total);assertNull(service.summary(q()).data);}
    @Test void sourceFaultIs503()throws Exception{when(source.events(anyString(),anyString())).thenThrow(new IllegalStateException("secret"));for(String p:Arrays.asList("","/summary"))mvc.perform(get("/api/portal/v1/events"+p).param("siteId","s")).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.errorCode").value("SOURCE_UNAVAILABLE"));}
    @Test void subresourceFaultDoesNotBecomeEmpty(){when(source.timeline(anyString(),anyString(),anyString())).thenThrow(new RuntimeException());assertEquals(503,assertThrows(PortalException.class,()->service.timeline(q(),"e")).status);assertNotNull(service.detail(q(),"e"));}
    @Test void relatedModulePermissionsHideData(){login("portal:event:read");Detail d=detail();d.event.person=Section.available(Arrays.asList(ref("p")));d.materials=Section.available(Arrays.asList(evidence("m")));when(source.detail("101","s","e")).thenReturn(d);Detail out=service.detail(q(),"e");assertEquals(State.FORBIDDEN,out.event.person.state);assertNull(out.event.person.data);assertNull(out.materials.data);assertEquals(State.FORBIDDEN,out.verificationDelivery.state);}
    @Test void relatedObjectScopeAndHistoricalProof(){Detail d=detail();Ref p=ref("p");p.attribution="UNKNOWN";d.event.person=Section.available(Arrays.asList(p));d.video=Section.available(Arrays.asList(ref("hidden")));d.materials=Section.available(Arrays.asList(evidence("hidden")));when(source.detail("101","s","e")).thenReturn(d);Detail out=service.detail(q(),"e");assertEquals("HISTORICAL_ATTRIBUTION_UNKNOWN",out.event.person.reasonCode);assertNull(out.video.data);assertNull(out.materials.data);}
    @Test void missingDeviceScopeRedactsCode(){Fact f=fact("e");f.deviceId="hidden";when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(f)));assertNull(service.list(q()).items.get(0).deviceCode);}
    @Test void unknownLocationEvidenceDoesNotUseCurrentPosition(){Detail d=detail();PortalEventModels.Position p=new PortalEventModels.Position();p.id="loc";p.siteId="s";p.longitude=0D;p.latitude=0D;d.location=Section.available(p);when(source.detail("101","s","e")).thenReturn(d);assertNull(service.detail(q(),"e").location.data);}
    @Test void confirmedZeroCoordinateRetained(){Detail d=detail();PortalEventModels.Position p=new PortalEventModels.Position();p.id="loc";p.siteId="s";p.longitude=0D;p.latitude=0D;p.attribution="CONFIRMED";p.evidenceId="proof";d.location=Section.available(p);when(source.detail("101","s","e")).thenReturn(d);assertEquals(0D,service.detail(q(),"e").location.data.longitude);}
    @Test void duplicateEventAndSourceIdentity(){Fact a=fact("a"),b=fact("b");b.sourceEventId=a.sourceEventId;b.sourceSystem="SECOND";when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(a,a,b)));assertEquals(2L,service.list(q()).total);b.sourceSystem=a.sourceSystem;assertEquals(503,assertThrows(PortalException.class,()->service.list(q())).status);}
    @Test void conflictingEventIdentityRejected(){Fact a=fact("a"),b=fact("a");b.sourceSystem="SECOND";when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(a,b)));assertThrows(PortalException.class,()->service.list(q()));}
    @Test void longIdsStayStrings()throws Exception{when(source.events(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(fact("90071992547409931234"))));mvc.perform(get("/api/portal/v1/events").param("siteId","s")).andExpect(jsonPath("$.data.items[0].eventId").value("90071992547409931234"));}
    @Test void statisticsAreIndependentAndMutuallyExclusive(){assertNull(service.summary(q()).data);StatisticsEvidence s=new StatisticsEvidence();s.events.put("e",Phase.UNKNOWN);when(source.statistics(anyString(),any())).thenReturn(Section.available(s));Statistics out=service.summary(q()).data;assertEquals(1,out.counts.get(Phase.UNKNOWN));assertEquals(0,out.counts.get(Phase.UNCLAIMED));s.events.put("hidden",Phase.LOCAL_COMPLETED);assertThrows(PortalException.class,()->service.summary(q()));}
    @Test void draftNotSubmittedAndUnconfirmedNotCompleted(){Verification v=verification("v");v.conclusion="UNCONFIRMED";when(source.verifications(anyString(),anyString(),anyString())).thenReturn(Section.available(Arrays.asList(v)));assertEquals(VerificationState.DRAFT,service.verifications(q(),"e").items.get(0).state);assertEquals(Phase.UNKNOWN,service.detail(q(),"e").event.phase);v.submittedAt="2026-09-01T00:00:00Z";assertThrows(PortalException.class,()->service.verifications(q(),"e"));}
    @Test void verificationEvidenceNeedsMaterialPermission(){login("portal:event:read","portal:event:verification:read");Verification v=verification("v");v.evidence=Section.available(Arrays.asList(evidence("m")));when(source.verifications(anyString(),anyString(),anyString())).thenReturn(Section.available(Arrays.asList(v)));assertEquals(State.FORBIDDEN,service.verifications(q(),"e").items.get(0).evidence.state);}
    @Test void timelineStableSequenceUnknownTime(){Timeline a=new Timeline(),b=new Timeline();a.id="a";b.id="b";for(Timeline t:Arrays.asList(a,b)){t.siteId="s";t.eventId="e";t.title="事实";t.kind="SOURCE";}a.sequence=2;b.sequence=1;when(source.timeline(anyString(),anyString(),anyString())).thenReturn(Section.available(Arrays.asList(a,b)));PortalEventQuery q=q();q.pageSize=1;Page<Timeline>p=service.timeline(q,"e");assertEquals("b",p.items.get(0).id);assertNull(p.items.get(0).sourceTime);q.pageNum=2;assertEquals("a",service.timeline(q,"e").items.get(0).id);}
    @Test void recordBelongsToRequestedEvent(){Verification v=verification("v");v.eventId="other";when(source.verifications(anyString(),anyString(),anyString())).thenReturn(Section.available(Arrays.asList(v)));assertThrows(PortalException.class,()->service.verifications(q(),"e"));}
    @Test void deliverySuccessDoesNotChangeLocalPhase(){Detail d=detail();Delivery r=new Delivery();r.state=DeliveryState.SUCCESS;d.summaryDelivery=Section.available(r);Delivery failed=new Delivery();failed.state=DeliveryState.FAILED;d.verificationDelivery=Section.available(failed);when(source.detail("101","s","e")).thenReturn(d);Detail out=service.detail(q(),"e");assertEquals(Phase.UNKNOWN,out.event.phase);assertEquals(DeliveryState.FAILED,out.verificationDelivery.data.state);}
    @Test void legacyMappingDoesNotCreateVerificationOrStation(){RealTimeAlarm a=new RealTimeAlarm();a.setId(9007199254740993123L);a.setIsHandled(1);a.setAlarmType("fall");a.setAlarmLevel("high");a.setUserName("不推定为人员");a.setUpdateTime(new Date());assertThrows(PortalException.class,()->PortalLegacyAlarmAdapter.map(a,"e",null,null));Fact f=PortalLegacyAlarmAdapter.map(a,"e","s",null);assertEquals(1,f.legacyHandled);assertEquals("fall",f.rawType);assertEquals(Phase.UNKNOWN,f.phase);assertEquals("UNKNOWN",f.eventType);assertNull(f.person.data);assertNull(f.occurredAt);assertNull(f.receivedAt);}
    @Test void defaultSourceNeverReadsOrGrants(){PortalEventSource s=new PortalEventConfiguration().portalEventSource();assertEquals(State.NOT_INTEGRATED,s.events("a","s").state);assertFalse(s.visible("a","s","event","e","portal:event:read"));assertNull(s.detail("a","s","e"));assertTrue(new Context().capabilities.containsKey("events"));}
    @Test void metadataNoSensitiveAddressFields(){for(Class<?> c:Arrays.asList(Fact.class,Ref.class,Evidence.class,Verification.class,Delivery.class,OriginalState.class))for(java.lang.reflect.Field f:c.getFields())assertFalse(f.getName().toLowerCase().matches(".*(url|path|token|credential|rtc).*"));}
}
