package com.ruoyi.portal;
import com.ruoyi.portal.PortalModels.*;
import com.ruoyi.portal.PortalVideoModels.*;
import com.ruoyi.portal.PortalVideoModels.Detail;
import com.ruoyi.common.core.domain.model.LoginUser;
import org.junit.jupiter.api.*;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.context.SecurityContextHolder;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;
import static org.mockito.ArgumentMatchers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
class PortalVideoTest {
    PortalSource context;PortalVideoSource source;PortalVideoService service;MockMvc mvc;
    @BeforeEach void setup(){login("*:*:*");context=mock(PortalSource.class);source=mock(PortalVideoSource.class);Context c=new Context();Site s=new Site();s.siteId="s";s.name="合成厂站";c.sites.add(s);when(context.context(anyString())).thenReturn(c);when(source.filters(anyString(),anyString())).thenAnswer(i->new Filters());when(source.visible(anyString(),eq("s"),anyString(),anyString(),anyString())).thenAnswer(i->!"hidden".equals(i.getArgument(3)));when(source.devices(anyString(),anyString())).thenAnswer(i->Section.available(Arrays.asList(device("d"))));when(source.statistics(anyString(),any())).thenReturn(Section.missing("STATISTICS_NOT_INTEGRATED"));when(source.detail(anyString(),eq("s"),eq("d"))).thenAnswer(i->detail());service=new PortalVideoService(new PortalAccess(),context,source);mvc=MockMvcBuilders.standaloneSetup(new PortalVideoController(service)).setControllerAdvice(new PortalExceptionHandler()).build();}
    @AfterEach void clear(){SecurityContextHolder.clearContext();}
    void login(String...p){LoginUser u=new LoginUser();u.setUserId(101L);u.setPermissions(new HashSet<>(Arrays.asList(p)));SecurityContextHolder.getContext().setAuthentication(new UsernamePasswordAuthenticationToken(u,null,Collections.emptyList()));}
    PortalVideoQuery q(){PortalVideoQuery q=new PortalVideoQuery();q.siteId="s";return q;}
    VideoDevice device(String id){VideoDevice d=new VideoDevice();d.deviceId=id;d.siteId="s";d.name="合成设备";d.type=DeviceType.HELMET;return d;}
    Related relation(String id){Related r=new Related();r.id=id;r.siteId="s";r.name="合成关联";r.attribution="CONFIRMED";r.evidenceId="evidence";return r;}
    Detail detail(){Detail d=new Detail();d.device=device("d");return d;}
    @Test void bothEndpointsRequireLogin()throws Exception{SecurityContextHolder.clearContext();for(String p:Arrays.asList("","/d"))mvc.perform(get("/api/portal/v1/video-sources"+p).param("siteId","s")).andExpect(status().isUnauthorized());verifyNoInteractions(source,context);}
    @Test void videoPermissionRequired()throws Exception{login("portal:person:read");for(String p:Arrays.asList("","/d"))mvc.perform(get("/api/portal/v1/video-sources"+p).param("siteId","s")).andExpect(status().isForbidden());verifyNoInteractions(source);}
    @Test void crossSiteRejected()throws Exception{for(String p:Arrays.asList("","/d"))mvc.perform(get("/api/portal/v1/video-sources"+p).param("siteId","other")).andExpect(status().isForbidden());verifyNoInteractions(source);}
    @Test void hiddenAndMissingReturn404()throws Exception{for(String id:Arrays.asList("hidden","missing"))mvc.perform(get("/api/portal/v1/video-sources/"+id).param("siteId","s")).andExpect(status().isNotFound());}
    @Test void envelopeAndLongIds()throws Exception{when(source.devices(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(device("90071992547409931234"))));mvc.perform(get("/api/portal/v1/video-sources").param("siteId","s")).andExpect(status().isOk()).andExpect(jsonPath("$.data.items[0].deviceId").value("90071992547409931234")).andExpect(jsonPath("$.data.total").value(1)).andExpect(jsonPath("$.requestId").isString());mvc.perform(get("/api/portal/v1/video-sources/d").param("siteId","s")).andExpect(status().isOk()).andExpect(jsonPath("$.data.device.unavailableReason").value("MEDIA_ACCESS_NOT_ENABLED"));}
    @Test void badParameters()throws Exception{for(String n:Arrays.asList("0","101","no"))mvc.perform(get("/api/portal/v1/video-sources").param("siteId","s").param("pageSize",n)).andExpect(status().isBadRequest());mvc.perform(get("/api/portal/v1/video-sources").param("siteId","s","other")).andExpect(status().isBadRequest());mvc.perform(get("/api/portal/v1/video-sources/d").param("siteId","s").param("url","x")).andExpect(status().isBadRequest());}
    @Test void unsupportedFilterExplicit()throws Exception{mvc.perform(get("/api/portal/v1/video-sources").param("siteId","s").param("areaId","a")).andExpect(status().isBadRequest()).andExpect(jsonPath("$.errorCode").value("FILTER_NOT_SUPPORTED"));}
    @Test void authorizedFilteringAndPagination(){Filters f=new Filters();Option o=new Option();o.id="a";o.name="合成区域";f.areas=Section.available(Arrays.asList(o));when(source.filters(anyString(),anyString())).thenReturn(f);VideoDevice d=device("d"),e=device("e");d.areaId="a";when(source.devices(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(d,e,d,device("hidden"))));PortalVideoQuery q=q();q.areaId="a";q.pageSize=1;assertEquals(1L,service.list(q).total);q.pageNum=2;assertTrue(service.list(q).items.isEmpty());}
    @Test void deduplicateBeforePagination(){when(source.devices(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(device("d"),device("d"),device("hidden"))));assertEquals(1L,service.list(q()).total);}
    @Test void sourceFailureNeverBecomesEmpty()throws Exception{when(source.devices(anyString(),anyString())).thenThrow(new RuntimeException("secret"));mvc.perform(get("/api/portal/v1/video-sources").param("siteId","s")).andExpect(status().isServiceUnavailable()).andExpect(jsonPath("$.errorCode").value("SOURCE_UNAVAILABLE"));when(source.detail(anyString(),anyString(),anyString())).thenThrow(new RuntimeException());mvc.perform(get("/api/portal/v1/video-sources/d").param("siteId","s")).andExpect(status().isServiceUnavailable());}
    @Test void sectionPermissionsDoNotLeak(){login("portal:video:read");Detail d=detail();d.person=Section.available(Arrays.asList(relation("p")));d.materials=Section.available(Arrays.asList(relation("m")));when(source.detail("101","s","d")).thenReturn(d);Detail r=service.detail(q(),"d");assertEquals(State.FORBIDDEN,r.person.state);assertNull(r.person.data);assertNull(r.materials.data);}
    @Test void historicalEvidenceNotInferred(){Detail d=detail();Related p=relation("p");p.attribution="UNKNOWN";d.person=Section.available(Arrays.asList(p));when(source.detail("101","s","d")).thenReturn(d);assertEquals("HISTORICAL_ATTRIBUTION_UNKNOWN",service.detail(q(),"d").person.reasonCode);}
    @Test void invisibleRelatedObjectNotExposed(){Detail d=detail();d.materials=Section.available(Arrays.asList(relation("hidden")));when(source.detail("101","s","d")).thenReturn(d);assertNull(service.detail(q(),"d").materials.data);}
    @Test void localSectionFailureIndependent(){Detail d=detail();d.events=new Section<>(State.UNAVAILABLE,null,"SOURCE_UNAVAILABLE");when(source.detail("101","s","d")).thenReturn(d);assertEquals(State.UNAVAILABLE,service.detail(q(),"d").events.state);}
    @Test void noSourceTimeDoesNotBorrowReceipt(){VideoDevice d=device("d");d.communication.state=CommunicationState.ONLINE;d.streamState=StreamState.INTERRUPTED;d.freshness=Freshness.FRESH;d.communication.receivedAt="2026-09-01T00:00:00Z";when(source.devices(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(d)));VideoDevice r=service.list(q()).items.get(0);assertNull(r.sourceTime);assertEquals(Freshness.UNKNOWN,r.freshness);assertEquals(CommunicationState.ONLINE,r.communication.state);assertEquals(StreamState.INTERRUPTED,r.streamState);}
    @Test void statisticsNeedIndependentCompleteEvidence(){assertNull(service.list(q()).statistics.data);StatisticsEvidence e=new StatisticsEvidence();e.deviceIds.add("d");e.availableIds.add("d");when(source.statistics(anyString(),any())).thenReturn(Section.available(e));assertEquals(1L,service.list(q()).statistics.data.available);e.deviceIds.add("hidden");assertEquals(503,assertThrows(PortalException.class,()->service.list(q())).status);}
    @Test void defaultsProvideNoDataOrVisibility(){PortalVideoSource s=new PortalVideoConfiguration().portalVideoSource();assertFalse(s.visible("a","s","device","d","portal:video:read"));assertEquals(State.NOT_INTEGRATED,s.devices("a","s").state);assertNull(s.detail("a","s","d"));assertTrue(new Context().capabilities.containsKey("video"));}
    @Test void listWorkAssociationStillNeedsModulePermission(){login("portal:video:read");VideoDevice d=device("d");d.workId="w";when(source.devices(anyString(),anyString())).thenReturn(Section.available(Arrays.asList(d)));assertNull(service.list(q()).items.get(0).workId);}
    @Test void publicVideoDTOHasNoAddressesOrCredentials(){for(Class<?> c:Arrays.asList(VideoDevice.class,Related.class,Statistics.class,Detail.class))for(java.lang.reflect.Field f:c.getFields())assertFalse(f.getName().toLowerCase().matches(".*(url|token|path|credential|rtc).*"));}
}
