<template>
  <div class="app-container">
    <ModuleHeader title="产品型号" description="统一维护安全帽与安全带的型号、协议和能力。停用型号不会影响已登记设备。" />
    <el-form class="search-form" :inline="true" :model="query"><el-form-item label="产品类型"><el-select v-model="query.typeCode" clearable class="w-160" placeholder="全部"><el-option label="安全帽" value="helmet"/><el-option label="安全带" value="belt"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" class="w-140"><el-option label="全部" value="all"/><el-option label="启用" value="0"/><el-option label="停用" value="1"/></el-select></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="load">查询</el-button></el-form-item></el-form>
    <div class="page-toolbar"><el-button v-if="canWrite" type="primary" icon="Plus" @click="openForm()">新增型号</el-button><el-button v-if="canWrite" icon="Upload" @click="importOpen=true">批量导入</el-button><el-button icon="Download" @click="downloadExport('product-models',{...query},'产品型号.xlsx')">导出</el-button></div>
    <el-table v-loading="loading" class="custom-table" :data="list"><template #empty><BrandedEmpty compact description="暂无产品型号" /></template><el-table-column label="型号编码" prop="modelCode" min-width="150"/><el-table-column label="型号名称" prop="name" min-width="180"/><el-table-column label="类型" width="100"><template #default="s">{{ typeLabel(s.row.typeCode) }}</template></el-table-column><el-table-column label="厂商" prop="manufacturerCode" min-width="130"/><el-table-column label="协议版本" prop="protocolVersion" width="120"/><el-table-column label="能力" min-width="220"><template #default="s"><el-tag v-for="cap in capabilityList(s.row)" :key="cap" size="small" class="mr4">{{ cap }}</el-tag><span v-if="!capabilityList(s.row).length">—</span></template></el-table-column><el-table-column label="状态" width="90"><template #default="s"><el-tag :type="s.row.status === '0' ? 'success' : 'info'" size="small">{{ s.row.status === '0' ? '启用' : '停用' }}</el-tag></template></el-table-column><el-table-column v-if="canWrite" label="操作" width="180" fixed="right"><template #default="s"><el-button link type="primary" @click="openForm(s.row)">编辑</el-button><el-button link :type="s.row.status === '0' ? 'danger' : 'success'" @click="toggle(s.row)">{{ s.row.status === '0' ? '停用' : '恢复' }}</el-button></template></el-table-column></el-table>
    <el-drawer v-model="formOpen" :title="form.id ? '编辑产品型号' : '新增产品型号'" size="520px" destroy-on-close><el-form ref="formRef" :model="form" :rules="rules" label-position="top"><el-form-item label="型号编码" prop="modelCode"><el-input v-model="form.modelCode" :disabled="!!form.id"/></el-form-item><el-form-item label="型号名称" prop="name"><el-input v-model="form.name"/></el-form-item><div class="form-grid"><el-form-item label="产品类型" prop="typeCode"><el-select v-model="form.typeCode"><el-option label="安全帽" value="helmet"/><el-option label="安全带" value="belt"/></el-select></el-form-item><el-form-item label="厂商编码" prop="manufacturerCode"><el-input v-model="form.manufacturerCode"/></el-form-item></div><el-form-item label="协议版本"><el-input v-model="form.protocolVersion"/></el-form-item><el-form-item label="设备能力"><el-checkbox-group v-model="form.actions"><el-checkbox label="intercom">对讲</el-checkbox><el-checkbox label="video">视频</el-checkbox><el-checkbox label="tts">语音播报</el-checkbox></el-checkbox-group></el-form-item></el-form><template #footer><el-button @click="formOpen=false">取消</el-button><el-button type="primary" :loading="submitting" @click="submit">保存更改</el-button></template></el-drawer>
    <LedgerImportDialog v-model="importOpen" resource="product-models" template-name="产品型号导入模板.xlsx" @success="load" />
  </div>
</template>
<script setup>
import { listProductModels, createProductModel, updateProductModel, changeProductModelStatus } from '@/api/wear/devices'; import useUserStore from '@/store/modules/user'; import { downloadExport } from '@/api/wear/admin'; import LedgerImportDialog from '@/components/LedgerImportDialog/index.vue'
const userStore=useUserStore(); const {proxy}=getCurrentInstance(); const canWrite=computed(()=>userStore.canWriteDevice); const loading=ref(false); const submitting=ref(false); const list=ref([]); const query=reactive({typeCode:'',status:'all'}); const formOpen=ref(false); const importOpen=ref(false); const formRef=ref(); const form=reactive({id:'',modelCode:'',name:'',typeCode:'helmet',manufacturerCode:'MELHAT',protocolVersion:'',actions:[],version:1}); const rules={modelCode:[{required:true,message:'请输入型号编码',trigger:'blur'}],name:[{required:true,message:'请输入型号名称',trigger:'blur'}],typeCode:[{required:true,message:'请选择产品类型',trigger:'change'}],manufacturerCode:[{required:true,message:'请输入厂商编码',trigger:'blur'}]}
function unwrap(r){return r?.data!==undefined?r.data:r} function typeLabel(v){return v==='helmet'?'安全帽':v==='belt'?'安全带':v||'—'} function capabilityList(row){return row.capabilities?.actions||[]} function load(){loading.value=true;listProductModels(query).then(r=>{list.value=unwrap(r)||[]}).finally(()=>{loading.value=false})} function openForm(row={}){Object.assign(form,{id:row.id||'',modelCode:row.modelCode||'',name:row.name||'',typeCode:row.typeCode||'helmet',manufacturerCode:row.manufacturerCode||'MELHAT',protocolVersion:row.protocolVersion||'',actions:[...(row.capabilities?.actions||[])],version:row.version||1});formOpen.value=true} function submit(){formRef.value.validate(v=>{if(!v)return;submitting.value=true;const payload={...form,capabilities:{protocolVersion:form.protocolVersion,attributes:[],events:[],actions:form.actions}};const req=form.id?updateProductModel(form.id,payload):createProductModel(payload);req.then(()=>{proxy.$modal.msgSuccess('保存成功');formOpen.value=false;load()}).finally(()=>{submitting.value=false})})} function toggle(row){proxy.$modal.confirm(`确认${row.status==='0'?'停用':'恢复'}“${row.name}”吗？`).then(()=>changeProductModelStatus(row.id,{status:row.status==='0'?'1':'0',version:row.version})).then(()=>{proxy.$modal.msgSuccess('状态已更新');load()}).catch(()=>{})} onMounted(load)
</script>
<style scoped>.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.mr4{margin-right:4px}.w-160{width:160px}.w-140{width:140px}</style>
