<template>
  <div class="app-container">
    <ModuleHeader title="事件记录" description="只读审计台账。事件认领、处置、转交与关闭统一在安卓端完成。" />
    <el-form class="search-form" :inline="true" :model="query"><el-form-item label="事件类型"><el-select v-model="query.type" clearable class="w-140" placeholder="全部"><el-option label="SOS" value="sos"/><el-option label="坠落" value="fall"/><el-option label="冲击" value="impact"/><el-option label="围栏" value="geofence"/><el-option label="实时告警" value="realtime"/></el-select></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable class="w-140" placeholder="全部"><el-option v-for="item in statuses" :key="item.value" :label="item.label" :value="item.value"/></el-select></el-form-item><el-form-item label="人员"><el-input v-model="query.personKeyword" clearable placeholder="姓名或人员标识"/></el-form-item><el-form-item label="设备"><el-input v-model="query.sn" clearable placeholder="设备序列号"/></el-form-item><el-form-item label="任务"><el-input v-model="query.taskId" clearable placeholder="任务ID"/></el-form-item><el-form-item label="发生日期"><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="search">查询</el-button><el-button icon="Refresh" @click="reset">重置</el-button></el-form-item></el-form>
    <div class="page-toolbar"><el-button icon="Download" @click="doExport">导出筛选结果</el-button><span class="toolbar-note">共 {{ total }} 条记录</span></div>
    <el-table v-loading="loading" class="custom-table" :data="list" @row-dblclick="openDetail"><template #empty><BrandedEmpty compact description="暂无事件记录" /></template><el-table-column label="事件编号" prop="id" width="110"/><el-table-column label="类型" width="100"><template #default="s"><el-tag :type="typeTag(s.row.type)" effect="plain" size="small">{{ eventTypeLabel(s.row.type) }}</el-tag></template></el-table-column><el-table-column label="级别" width="90"><template #default="s">{{ severityLabel(s.row.severity) }}</template></el-table-column><el-table-column label="状态" width="105"><template #default="s"><el-tag :type="statusTag(s.row.status)" size="small">{{ eventStatusLabel(s.row.status) }}</el-tag></template></el-table-column><el-table-column label="人员" min-width="140"><template #default="s">{{ s.row.personName||'未知' }} <span class="muted">{{ s.row.personCode }}</span></template></el-table-column><el-table-column label="设备" prop="sn" min-width="140"><template #default="s">{{ s.row.sn||'未知' }}</template></el-table-column><el-table-column label="发生时间" prop="occurredAt" width="190"/><el-table-column label="关联任务" width="120"><template #default="s">{{ s.row.taskId ? '#'+s.row.taskId : '—' }}</template></el-table-column><el-table-column label="操作" width="90" fixed="right"><template #default="s"><el-button link type="primary" @click="openDetail(s.row)">详情</el-button></template></el-table-column></el-table>
    <pagination v-show="total>0" v-model:page="query.current" v-model:limit="query.size" :total="total" @pagination="load"/>
    <el-drawer v-model="detailOpen" title="事件审计详情" size="600px"><el-descriptions v-if="detail.id" :column="2" border><el-descriptions-item label="事件编号">{{ detail.id }}</el-descriptions-item><el-descriptions-item label="状态">{{ eventStatusLabel(detail.status) }}</el-descriptions-item><el-descriptions-item label="人员">{{ detail.personName||'未知' }}</el-descriptions-item><el-descriptions-item label="设备">{{ detail.sn||'未知' }}</el-descriptions-item><el-descriptions-item label="发生时间" :span="2">{{ detail.occurredAt||'—' }}</el-descriptions-item><el-descriptions-item label="位置" :span="2">{{ locationText(detail) }}</el-descriptions-item><el-descriptions-item label="来源">{{ sourceLabel(detail.source) }}</el-descriptions-item><el-descriptions-item label="重复次数">{{ detail.repeatCount||0 }}</el-descriptions-item><el-descriptions-item label="作业任务" :span="2">{{ detail.taskId?'#'+detail.taskId:'未关联' }}</el-descriptions-item></el-descriptions><h3 class="drawer-section-title">动作时间线</h3><el-timeline><el-timeline-item v-for="item in actions" :key="item.id" :timestamp="item.createTime"><strong>{{ actionLabel(item.action) }}</strong> · {{ item.actor||'系统' }}<p v-if="item.reason">{{ item.reason }}</p></el-timeline-item></el-timeline><BrandedEmpty v-if="!actions.length" compact description="暂无动作记录"/></el-drawer>
  </div>
</template>
<script setup>
import {listEvents,getEvent,listEventActions,eventTypeLabel,eventStatusLabel} from '@/api/wear/events'; import {downloadExport} from '@/api/wear/admin'; const loading=ref(false);const list=ref([]);const total=ref(0);const dateRange=ref([]);const query=reactive({current:1,size:10,type:'',status:'all',personKeyword:'',sn:'',taskId:'',occurredFrom:'',occurredTo:''});const detailOpen=ref(false);const detail=ref({});const actions=ref([]);const statuses=[{label:'全部状态',value:'all'},{label:'待认领',value:'open'},{label:'已认领',value:'claimed'},{label:'处置中',value:'handling'},{label:'待复核',value:'pending_review'},{label:'已关闭',value:'closed'}];function unwrap(r){return r?.data!==undefined?r.data:r}function syncDates(){query.occurredFrom=dateRange.value?.[0]||'';query.occurredTo=dateRange.value?.[1]||''}function load(){syncDates();loading.value=true;listEvents(query).then(r=>{const p=unwrap(r)||{};list.value=p.records||[];total.value=p.total||0}).finally(()=>{loading.value=false})}function search(){query.current=1;load()}function reset(){Object.assign(query,{current:1,type:'',status:'all',personKeyword:'',sn:'',taskId:'',occurredFrom:'',occurredTo:''});dateRange.value=[];load()}function doExport(){syncDates();downloadExport('events',{...query},'事件记录.xlsx')}function openDetail(row){detailOpen.value=true;Promise.all([getEvent(row.id),listEventActions(row.id)]).then(([a,b])=>{detail.value=unwrap(a)||row;actions.value=unwrap(b)||[]})}function severityLabel(v){return {high:'高',medium:'中',low:'低'}[v]||v||'—'}function sourceLabel(v){return {helmet:'设备上报',simulator:'模拟器',geofence:'围栏规则'}[v]||v||'—'}function actionLabel(v){return {ack:'已看见',claim:'认领',handle:'处置',transfer:'转交',close:'关闭',reopen:'重开',escalate:'升级',review:'复核'}[v]||v}function locationText(r){return r.locationLat==null||r.locationLng==null?'无有效坐标':`${r.locationLat}, ${r.locationLng}（${r.locationQuality==='ok'?'有效':r.locationQuality==='stale'?'陈旧':'未知'}）`}function statusTag(v){return v==='closed'?'info':v==='pending_review'?'warning':v==='handling'?'primary':'danger'}function typeTag(v){return v==='sos'||v==='fall'?'danger':v==='geofence'?'warning':'info'}function onSiteChanged(){search()}onMounted(()=>{load();window.addEventListener('site-changed',onSiteChanged)});onUnmounted(()=>window.removeEventListener('site-changed',onSiteChanged))
</script><style scoped>.w-140{width:140px}.muted,.toolbar-note{color:var(--text-muted);font-size:12px}.toolbar-note{margin-left:auto}.drawer-section-title{margin:24px 0 16px;font-size:15px}</style>
