<template>
  <div class="app-container">
    <ModuleHeader title="领用归还记录" description="集中核对设备领用、正常归还与异常回收记录，所有历史只追加不删除。" />
    <el-form class="search-form" :inline="true" :model="query"><el-form-item label="设备序列号"><el-input v-model="query.sn" clearable placeholder="SN" @keyup.enter="search"/></el-form-item><el-form-item label="人员"><el-input v-model="query.personKeyword" clearable placeholder="姓名或人员标识" @keyup.enter="search"/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable class="w-140" placeholder="全部"><el-option label="领用中" value="active"/><el-option label="已归还" value="returned"/></el-select></el-form-item><el-form-item label="领用日期"><el-date-picker v-model="dateRange" type="daterange" value-format="YYYY-MM-DD" start-placeholder="开始日期" end-placeholder="结束日期"/></el-form-item><el-form-item><el-button type="primary" icon="Search" @click="search">查询</el-button><el-button icon="Refresh" @click="reset">重置</el-button></el-form-item></el-form>
    <div class="page-toolbar"><el-button icon="Download" @click="doExport">导出筛选结果</el-button></div>
    <el-table v-loading="loading" class="custom-table" :data="list"><template #empty><BrandedEmpty compact description="暂无领用归还记录" /></template><el-table-column label="设备序列号" prop="sn" min-width="160"/><el-table-column label="设备类型" width="100"><template #default="s">{{ s.row.typeCode==='helmet'?'安全帽':s.row.typeCode==='belt'?'安全带':'—' }}</template></el-table-column><el-table-column label="领用人员" min-width="170"><template #default="s">{{ s.row.personName }} <span class="muted">{{ s.row.personCode }}</span></template></el-table-column><el-table-column label="领用时间" prop="issuedAt" width="190"/><el-table-column label="归还时间" width="190"><template #default="s">{{ s.row.returnedAt||'—' }}</template></el-table-column><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.returnedAt?'info':'success'" size="small">{{ s.row.returnedAt?'已归还':'领用中' }}</el-tag></template></el-table-column><el-table-column label="归还方式" width="110"><template #default="s">{{ s.row.returnKind==='recover'?'异常回收':s.row.returnedAt?'正常归还':'—' }}</template></el-table-column><el-table-column label="经办人" min-width="130"><template #default="s">{{ s.row.returnedBy||s.row.issuedBy||'—' }}</template></el-table-column><el-table-column label="说明" prop="returnReason" min-width="180" show-overflow-tooltip/></el-table>
    <pagination v-show="total>0" v-model:page="query.current" v-model:limit="query.size" :total="total" @pagination="load"/>
  </div>
</template>
<script setup>
import { listAssignments } from '@/api/wear/assignments'; import { downloadExport } from '@/api/wear/admin'; const loading=ref(false); const list=ref([]); const total=ref(0); const dateRange=ref([]); const query=reactive({current:1,size:10,sn:'',personKeyword:'',status:'',issuedFrom:'',issuedTo:''}); function unwrap(r){return r?.data!==undefined?r.data:r} function syncDates(){query.issuedFrom=dateRange.value?.[0]||'';query.issuedTo=dateRange.value?.[1]||''} function load(){syncDates();loading.value=true;listAssignments(query).then(r=>{const p=unwrap(r)||{};list.value=p.records||[];total.value=p.total||0}).finally(()=>{loading.value=false})} function search(){query.current=1;load()} function reset(){Object.assign(query,{current:1,sn:'',personKeyword:'',status:'',issuedFrom:'',issuedTo:''});dateRange.value=[];load()} function doExport(){syncDates();downloadExport('assignments',{...query},'领用归还记录.xlsx')} function onSiteChanged(){search()} onMounted(()=>{load();window.addEventListener('site-changed',onSiteChanged)});onUnmounted(()=>window.removeEventListener('site-changed',onSiteChanged))
</script><style scoped>.w-140{width:140px}.muted{margin-left:5px;color:var(--text-muted);font-size:12px}</style>
