const { chromium }=require('C:/Users/qiyue/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),{pathToFileURL}=require('url');
const root=path.resolve(__dirname,'..');
(async()=>{
 const browser=await chromium.launch({headless:true,channel:'chrome'});
 const page=await browser.newPage({viewport:{width:1440,height:1060},deviceScaleFactor:1});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 const manifest=JSON.parse(fs.readFileSync(path.join(root,'manifest.json'),'utf8'));
 await page.goto(pathToFileURL(path.join(root,'index.html')).href);
 await page.locator('.card').last().waitFor();
 await page.waitForFunction(()=>[...document.querySelectorAll('.card img')].slice(0,4).every(i=>i.complete&&i.naturalWidth>0));
 if(await page.locator('.card').count()!==42)throw Error('Gallery count mismatch');
 await page.screenshot({path:path.join(root,'tools/网页总览验收.png'),fullPage:false});
 await page.getByRole('button',{name:'现场',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.card').length===13);
 await page.getByRole('button',{name:'全部',exact:true}).click();
 await page.waitForFunction(()=>document.querySelectorAll('.card').length===42);
 await page.getByRole('searchbox').fill('SOS');
 if(await page.locator('.card').count()<1)throw Error('Search failed');
 await page.getByRole('searchbox').fill('');
 await page.locator('#view-map').click();
 await page.locator('.tree-link').last().waitFor();
 if(await page.locator('.tree-link').count()!==42)throw Error('Tree duplicates or omissions');
 await page.screenshot({path:path.join(root,'tools/父子关系验收.png'),fullPage:true});
 const checks=[];
 for(const item of manifest.items){
   await page.goto(pathToFileURL(path.join(root,'pages',item.id+'.html')).href);
   await page.locator('.long-wrap img').waitFor();
   await page.waitForFunction(()=>[...document.images].every(i=>i.complete));
   if(await page.locator('.long-wrap img').evaluate(i=>i.naturalWidth)!==1080)throw Error('Broken image '+item.id);
   const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);
   if(overflow)throw Error('Desktop overflow '+item.id);
   const last=item.frames.at(-1); if(Math.abs(last.offset-last.max)>1)throw Error('Missing bottom '+item.id);
   await page.locator('[data-mode="frames"]').click();
   if(await page.locator('.frame').count()!==item.frames.length)throw Error('Frames mismatch '+item.id);
   const parentLinks=await page.locator('.relation').count();
   checks.push({id:item.id,frames:item.frames.length,parentLinks,images:true,bottom:true});
 }
 await page.goto(pathToFileURL(path.join(root,'pages/25.html')).href);
 await page.screenshot({path:path.join(root,'tools/长页面验收.png'),fullPage:true});
 await page.locator('.relation').first().click();
 if(!page.url().includes('/22.html'))throw Error('Parent navigation failed');
 await page.setViewportSize({width:390,height:844});
 await page.goto(pathToFileURL(path.join(root,'index.html')).href);
 await page.waitForFunction(()=>[...document.querySelectorAll('.card img')].slice(0,2).every(i=>i.complete&&i.naturalWidth>0));
 await page.screenshot({path:path.join(root,'tools/手机宽度验收.png'),fullPage:false});
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile overview overflow');
 await page.goto(pathToFileURL(path.join(root,'pages/25.html')).href);
 if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1))throw Error('Mobile detail overflow');
 if(errors.length)throw Error(errors.join('\n'));
 fs.writeFileSync(path.join(root,'网页验收.json'),JSON.stringify({verifiedAt:new Date().toISOString(),protocol:'file:// (直接双击离线打开)',desktop:'1440x1060',mobile:'390x844',search:true,moduleFilters:true,treeNodes:42,parentNavigation:true,consoleErrors:errors,checks},null,2));
 await browser.close();console.log('PASS: 42 pages, image integrity, bottom coverage, filters, search, tree, parent navigation, desktop and mobile.');
})().catch(e=>{console.error(e);process.exit(1)});
