<template>
  <section :aria-busy="busy || record.loading.value">
    <div class="page-heading"><div><span class="eyebrow">管理中心 / 接入配置</span><h1>{{ isJob ? '模拟同步任务' : isDetail ? '外部系统连接设置' : '外部系统连接演示' }}</h1><p class="muted">仅处理本后台演示数据，不访问外部系统；测试通过仍为未接入。</p></div><span class="badge">当前页面 · 模拟</span></div>
    <nav class="workspace-tabs" aria-label="接入配置导航"><router-link :to="link('/admin/integrations')">六类连接器</router-link><router-link :to="link('/admin/integrations/settings')">演示参数</router-link></nav>
    <p v-if="notice" class="notice" role="status">{{ notice }} <router-link v-if="auditAllowed" :to="link('/admin/audit')">查看审计记录</router-link></p>
    <div v-if="actionError" ref="errorBox" class="notice error" role="alert" tabindex="-1"><strong>{{ actionError.message }}</strong><p>{{ actionError.errorCode }} · {{ actionError.requestId }}</p><p v-if="actionError.code === 409">配置或目标版本已变化，请返回连接器重新读取配置并重新预览。</p><button v-if="actionError.code === 409 && isDetail" class="button" :disabled="busy" @click="refresh">放弃修改并重新读取</button></div>
    <router-link v-if="isDetail || isJob" class="button" :to="back">返回连接器列表</router-link>
    <section v-if="!isDetail && !isJob" class="panel master-list"><form class="list-filters" @submit.prevent="navigate({ keyword, pageNum: '1' })"><label>连接器名称<input v-model="keyword" maxlength="100" /></label><button class="button primary">查询</button><button type="button" class="button" @click="navigate({ keyword: undefined, pageNum: '1' })">清除筛选</button></form>
      <QueryState :data="record.data.value" :loading="record.loading.value" :error="record.error.value" @retry="load"><div class="table-scroll"><table><caption class="sr-only">六类本地模拟连接器</caption><thead><tr><th>连接器</th><th>类型</th><th>真实状态</th><th>配置版本</th><th>操作</th></tr></thead><tbody><tr v-for="c in record.data.value?.rows || []" :key="c.id"><td>{{ c.name }}</td><td>{{ kinds[c.kind] }}</td><td>未接入</td><td>v{{ c.version }}</td><td><router-link class="button" :to="connectorLink(c.id)">配置与记录</router-link></td></tr></tbody></table></div><p v-if="!record.data.value?.rows?.length" class="query-state">暂无匹配连接器。</p><div class="pagination"><span>共 {{ record.data.value?.total || 0 }} 条 · 第 {{ pageNum }} 页</span><label>每页<select :value="pageSize" @change="navigate({ pageSize: $event.target.value, pageNum: '1' })"><option>20</option><option>50</option><option>100</option></select></label><button class="button" :disabled="pageNum <= 1" @click="navigate({ pageNum: String(pageNum - 1) })">上一页</button><button class="button" :disabled="pageNum * pageSize >= (record.data.value?.total || 0)" @click="navigate({ pageNum: String(pageNum + 1) })">下一页</button></div></QueryState>
    </section>
    <QueryState v-else :data="record.data.value" :loading="record.loading.value" :error="record.error.value" @retry="load"><template v-if="current?.id">
      <template v-if="isDetail"><section class="panel master-list"><div class="section-heading"><h2>{{ current.name }}</h2><span class="badge">未接入 · v{{ current.version }}</span></div><p>{{ kinds[current.kind] }} · {{ isSync ? '预览后确认导入模拟样本；保护现有领用、设备使用状态、授权及人工字段。' : '仅演示样本对应关系和独立回执，不生成作业、事件或结案记录。' }}</p>
        <p v-if="!writable" class="disabled-reason">无当前厂站接入配置维护权限，仅可查看。</p><form class="integration-form" @submit.prevent="act('update')"><fieldset :disabled="!writable || busy"><label>演示地址<select v-model="form.endpointKey"><option value="SAMPLE_A">mock://sample-a</option><option value="SAMPLE_B">mock://sample-b</option></select></label><label>演示登录信息<input value="MOCK-ONLY" readonly aria-label="演示登录信息，不可编辑" /></label><label>对应厂站<select v-model="form.mappedSiteId" @change="form.areaId = ''"><option value="">未选择厂站（无法导入）</option><option :value="store.siteId">{{ siteName }}</option></select></label><label>对应区域<select v-model="form.areaId" :disabled="!form.mappedSiteId"><option value="">未选择</option><option v-for="a in current.areas || []" :key="a.id" :value="a.id">{{ a.name }}</option></select></label><label>演示结果<select v-model="form.scenario"><option value="">使用厂站默认演示参数</option><option value="SUCCESS">成功</option><option value="TIMEOUT">模拟超时</option><option value="FIELD_MISMATCH">字段不匹配</option></select></label><button class="button primary" :disabled="!dirty">保存本地配置</button></fieldset></form>
        <p v-if="isSync && writable && !canSync" class="disabled-reason">导入样本还需要本厂站完整设备或人员查看及维护权限。</p><p v-if="dirty" class="notice">配置尚未保存，保存后才能测试或预览。</p><div class="actions"><button class="button" :disabled="!writable || busy || dirty" @click="act('test')">模拟测试</button><button v-if="isSync" class="button primary" :disabled="!canSync || busy || dirty" @click="act('preview')">预览模拟样本</button><button v-else class="button primary" :disabled="!writable || busy || dirty" @click="act('receipt')">生成模拟回执</button></div>
        <p v-if="current.lastTest" class="notice">{{ resultLabel(current.lastTest, true) }} · 配置 v{{ current.lastTest.configVersion }} · {{ current.lastTest.at }} UTC。真实状态仍为未接入。</p><p v-if="current.lastReceipt" class="notice">{{ resultLabel(current.lastReceipt) }} · 配置 v{{ current.lastReceipt.configVersion }} · {{ current.lastReceipt.source || '本后台演示数据' }}；未实际发送。</p>
        <details class="binding-card"><summary>测试与回执尝试记录（{{ current.attempts?.length || 0 }} 次）</summary><ol><li v-for="(attempt, index) in current.attempts || []" :key="index">{{ attempt.operation === 'RECEIPT' ? '模拟回执' : '模拟测试' }} · {{ resultLabel(attempt, attempt.operation !== 'RECEIPT') }} · 配置 v{{ attempt.configVersion }} · {{ attempt.at }} UTC</li></ol><p v-if="!current.attempts?.length">尚无尝试记录。</p></details><div v-if="!isSync" class="binding-card"><h3>演示数据对应范围</h3><p>来源：本后台演示数据。示例标识 → 当前厂站与所选区域；仅保存允许设置的数据对应关系。</p><p>{{ current.kind === 'WORK_TICKET' ? '工作票样本 → 本地对应关系演示，不创建作业台账。' : current.kind === 'SAFETY' ? '安监样本 → 本地对应关系演示，不创建事件台账。' : current.kind === 'SUMMARY_RETURN' ? '摘要回传 → 独立合成回执，不代表外部接收。' : '核验回传 → 独立合成回执，不代表核验或结案。' }}</p></div>
      </section><section v-if="isSync" class="panel master-list"><h2>同步任务与尝试记录</h2><QueryState :data="jobs.data.value" :loading="jobs.loading.value" :error="jobs.error.value" @retry="loadJobs"><article v-for="job in jobs.data.value?.rows || []" :key="job.id" class="binding-card"><router-link :to="jobLink(job.id)">{{ job.id }}</router-link><p>{{ statuses[job.status] }} · 配置 v{{ job.configVersion }} · {{ job.createdAt }} UTC</p></article><p v-if="!jobs.data.value?.rows?.length" class="muted">尚无模拟同步任务。</p><div class="pagination"><span>共 {{ jobs.data.value?.total || 0 }} 条 · 第 {{ jobsPage }} 页</span><button class="button" :disabled="jobsPage <= 1" @click="changeJobsPage(-1)">上一页任务</button><button class="button" :disabled="jobsPage * 20 >= (jobs.data.value?.total || 0)" @click="changeJobsPage(1)">下一页任务</button></div></QueryState></section></template>
      <section v-else class="panel master-list"><div class="section-heading"><h2>{{ current.id }}</h2><span class="badge">{{ statuses[current.status] }}</span></div><p>来源：{{ current.source }} · 配置 v{{ current.configVersion }} · 任务 v{{ current.version }}</p><p>新增 {{ current.counts?.created || 0 }} · 更新 {{ current.counts?.updated || 0 }} · 跳过 {{ current.counts?.skipped || 0 }} · 冲突 {{ current.counts?.conflicts || 0 }}</p><p v-if="current.status === 'CONFLICT'" class="notice error">存在冲突，整批禁止确认。请修正对应关系或来源身份冲突后重新预览。</p><p v-if="current.status === 'FAILED'" class="notice error">模拟处理失败，没有导入本批样本。可重试同一任务；重试会按当前配置重新预览，确认时再次校验版本。</p><p v-if="current.status === 'COMPLETED'" class="notice">模拟样本已处理，同一任务不会重复新增记录。</p><p v-if="!writable" class="disabled-reason">无当前厂站接入配置维护权限，不能确认或重试。</p><p v-if="writable && !canContinue" class="disabled-reason">仅预览任务创建人且具有本厂站对应台账完整查看及维护权限时可确认或重试。</p><div class="actions"><button class="button primary" :disabled="!canContinue || busy || current.status !== 'PREVIEW'" @click="confirmOpen = true">确认导入模拟样本</button><button v-if="['FAILED', 'CONFLICT'].includes(current.status)" class="button" :disabled="!canContinue || busy" @click="act('retry')">重试此任务</button><router-link class="button" :to="connectorLink(current.connectorId)">返回配置并重新预览</router-link></div>
        <div class="table-scroll"><table><caption>来源样本与预览结果</caption><thead><tr><th>来源标识</th><th>样本名称</th><th>计划动作</th><th>目标标识</th><th>原因</th></tr></thead><tbody><tr v-for="(row, index) in current.rows || []" :key="row.sourceId + '-' + index"><td>{{ row.sourceId }}</td><td>{{ row.name }}</td><td>{{ actions[row.action] || row.action }}</td><td>{{ row.targetId || '—' }}</td><td>{{ row.reason || '—' }}</td></tr></tbody></table></div><h3>每次尝试</h3><ol><li v-for="(attempt, index) in current.attempts || []" :key="index">{{ attempt.at }} UTC · {{ attempt.result }}</li></ol>
      </section>
    </template></QueryState>
    <ModalPanel :open="confirmOpen" heading-id="integration-confirm-heading" title="确认导入模拟样本" @close="!busy && (confirmOpen = false)"><p>仅将本后台演示数据写入当前厂站设备或人员台账。确认时会复核配置与目标版本；任一冲突将阻止整批导入。</p><p>新增 {{ current?.counts?.created || 0 }} · 更新 {{ current?.counts?.updated || 0 }} · 跳过 {{ current?.counts?.skipped || 0 }}</p><button class="button primary" :disabled="busy || !canContinue" @click="act('confirm')">确认导入模拟样本</button></ModalPanel>
  </section>
</template>
<script setup>
import { computed, reactive, ref, watch, nextTick, onBeforeUnmount } from 'vue'
import { useRoute, useRouter, onBeforeRouteLeave, onBeforeRouteUpdate } from 'vue-router'
import { getAdminProvider } from '@admin-provider'
import { useAdminStore } from '../store'
import { useQuery } from '../useQuery'
import { cleanIntegrationQuery, integrationReturn } from '../navigation'
import QueryState from '../components/QueryState.vue'
import ModalPanel from '../components/ModalPanel.vue'
const provider = getAdminProvider(), store = useAdminStore(), route = useRoute(), router = useRouter(), record = useQuery(), jobs = useQuery(), jobConnector = useQuery()
const kinds = { DEVICE: '设备同步', PERSON: '人员同步', WORK_TICKET: '工作票对应关系', SAFETY: '安监对应关系', SUMMARY_RETURN: '摘要回传', VERIFICATION_RETURN: '核验回传' }, statuses = { PREVIEW: '待确认预览', CONFLICT: '冲突阻止', FAILED: '模拟失败', COMPLETED: '已完成' }, actions = { CREATE: '新增', UPDATE: '更新', SKIP: '跳过', CONFLICT: '冲突' }
const isJob = computed(() => !!route.params.jobId), isDetail = computed(() => !!route.params.connectorId), current = computed(() => record.data.value), isSync = computed(() => ['DEVICE', 'PERSON'].includes(current.value?.kind)), query = computed(() => cleanIntegrationQuery(route.query)), pageNum = computed(() => Number(query.value.pageNum || 1)), pageSize = computed(() => Number(query.value.pageSize || 20)), back = computed(() => integrationReturn(route.query.returnTo))
const writable = computed(() => { void store.revision; return provider.can('integrations:write', store.siteId) }), auditAllowed = computed(() => { void store.revision; return provider.canAny('audit:read', store.siteId) }), siteName = computed(() => store.sites.find(s => s.id === store.siteId)?.name || store.siteId)
const canSync = computed(() => { void store.revision; return writable.value && ['read', 'write'].every(action => provider.can((current.value?.kind === 'PERSON' ? 'people:' : 'assets:') + action, store.siteId)) }), canContinue = computed(() => { void store.revision; return writable.value && current.value?.createdBy === provider.identity()?.id && ['DEVICE', 'PERSON'].includes(jobConnector.data.value?.kind) && ['read', 'write'].every(action => provider.can((jobConnector.data.value.kind === 'PERSON' ? 'people:' : 'assets:') + action, store.siteId)) })
const form = reactive({ endpointKey: 'SAMPLE_A', mappedSiteId: '', areaId: '', scenario: '' }), baseline = ref(''), draftVersion = ref(null), dirty = computed(() => !!baseline.value && JSON.stringify(form) !== baseline.value), busy = ref(false), notice = ref(''), actionError = ref(null), errorBox = ref(null), keyword = ref(''), jobsPage = ref(1), confirmOpen = ref(false)
let saveController, generation = 0, operation = null
const link = path => ({ path, query: { siteId: store.siteId } })
const connectorLink = id => ({ path: '/admin/integrations/' + id, query: { siteId: store.siteId, returnTo: !isDetail.value && !isJob.value ? route.fullPath : back.value } })
const jobLink = id => ({ path: '/admin/integrations/jobs/' + id, query: { siteId: store.siteId, returnTo: back.value } })
function navigate(patch) { router.replace({ path: '/admin/integrations', query: { ...query.value, ...patch, siteId: store.siteId } }) }
function hydrate() { const c = current.value; if (!isDetail.value || !c?.id) return; Object.assign(form, { endpointKey: c.endpointKey, mappedSiteId: c.mappedSiteId || '', areaId: c.areaId || '', scenario: c.scenario || '' }); baseline.value = JSON.stringify(form); draftVersion.value = c.version }
async function load() { const token = generation; await record.run(isJob.value ? 'integrationJob' : isDetail.value ? 'integration' : 'integrations', { ...query.value, siteId: store.siteId, id: route.params.jobId || route.params.connectorId, pageNum: pageNum.value, pageSize: pageSize.value }); if (token !== generation) return; if (!dirty.value) hydrate(); if (isDetail.value && current.value?.id) loadJobs(); if (isJob.value && current.value?.connectorId) jobConnector.run('integration', { siteId: store.siteId, id: current.value.connectorId }); if (!isDetail.value && !isJob.value && current.value?.total > 0 && !current.value.rows.length) navigate({ pageNum: String(Math.ceil(current.value.total / pageSize.value)) }) }
async function loadJobs() { if (!isSync.value) return; await jobs.run('integrationJobs', { siteId: store.siteId, connectorId: route.params.connectorId, pageNum: jobsPage.value, pageSize: 20 }); if (jobs.data.value?.total > 0 && !jobs.data.value.rows.length && jobsPage.value > 1) { jobsPage.value = Math.ceil(jobs.data.value.total / 20); loadJobs() } }
function changeJobsPage(step) { jobsPage.value += step; router.replace({ query: { ...route.query, pageNum: String(jobsPage.value) } }) }
async function refresh() { if (!allowLeave()) return; actionError.value = null; baseline.value = ''; await load() }
function resultLabel(result, test = false) { return result.result === 'SUCCESS' ? test ? '模拟测试通过' : '模拟回执成功' : result.result === 'TIMEOUT' ? '模拟超时' : '模拟字段不匹配' }
async function act(action) {
  if (!writable.value || busy.value || !current.value?.id || (action === 'preview' && !canSync.value) || (['confirm', 'retry'].includes(action) && !canContinue.value)) return
  const payload = { siteId: store.siteId, id: current.value.id, expectedVersion: action === 'update' ? draftVersion.value : current.value.version, ...(action === 'update' ? { endpointKey: form.endpointKey, mappedSiteId: form.mappedSiteId || null, areaId: form.areaId || null, scenario: form.scenario || null } : {}) }, fingerprint = JSON.stringify({ action, payload })
  if (operation?.fingerprint !== fingerprint) operation = { fingerprint, id: crypto.randomUUID() }
  const token = generation; saveController?.abort(); saveController = new AbortController(); busy.value = true; actionError.value = null
  try { const result = await provider.execute('integrations.' + action, { ...payload, operationId: operation.id }, { signal: saveController.signal }); if (token !== generation) return; operation = null; baseline.value = ''; confirmOpen.value = false; notice.value = action === 'test' ? resultLabel(result.data?.lastTest || {}, true) + '；真实状态仍为未接入。' : action === 'receipt' ? resultLabel(result.data?.lastReceipt || {}) + '；本后台演示数据，未实际发送。' : action === 'update' ? '本地配置已保存。' : '模拟任务已处理，请查看结果。'; if (action === 'preview') { busy.value = false; await router.push(jobLink(result.data.id)) } else await load() }
  catch (e) { if (token === generation && e.name !== 'AbortError') { actionError.value = e; confirmOpen.value = false; if (e.code === 401) provider.invalidate(); await nextTick(); await nextTick(); errorBox.value?.focus() } }
  finally { if (token === generation) busy.value = false }
}
function clear() { generation++; saveController?.abort(); record.cancel(); jobs.cancel(); jobConnector.cancel(); busy.value = false; baseline.value = ''; Object.assign(form, { endpointKey: 'SAMPLE_A', mappedSiteId: '', areaId: '', scenario: '' }); operation = null; confirmOpen.value = false; notice.value = ''; actionError.value = null }
function allowLeave() { if (busy.value) return false; if (dirty.value && !window.confirm('尚有未保存的接入配置，确定放弃吗？')) return false; baseline.value = ''; return true }
onBeforeRouteLeave(allowLeave)
onBeforeRouteUpdate((to, from) => to.params.connectorId === from.params.connectorId && to.params.jobId === from.params.jobId ? true : allowLeave())
store.leaveGuard = allowLeave
watch(form, () => { operation = null }, { flush: 'sync' })
const unsubscribe = provider.subscribe(({ kind }) => { if (['authorization', 'identity', 'expired', 'reset'].includes(kind)) clear() })
watch(() => store.siteId, clear, { flush: 'sync' })
watch(() => [route.params.connectorId, route.params.jobId], clear, { flush: 'sync' })
watch(() => [route.fullPath, store.siteId, store.revision], () => { keyword.value = query.value.keyword || ''; jobsPage.value = pageNum.value; load() }, { immediate: true })
const beforeUnload = event => { if (dirty.value) { event.preventDefault(); event.returnValue = '' } }
window.addEventListener('beforeunload', beforeUnload)
onBeforeUnmount(() => { clear(); unsubscribe(); if (store.leaveGuard === allowLeave) store.leaveGuard = null; window.removeEventListener('beforeunload', beforeUnload) })
</script>
<style scoped>
.integration-form fieldset{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px;border:0;padding:12px 0}.integration-form label{display:grid;gap:6px}.integration-form input,.integration-form select{width:100%;min-height:38px}.integration-form .button{justify-self:start}.actions{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}td{overflow-wrap:anywhere}table{width:100%}@media(max-width:700px){.integration-form fieldset{grid-template-columns:1fr}}
</style>

