<template><section><div class="page-heading"><div><span class="eyebrow">装备资产 / 运维办理</span><h1>维修与退役</h1><p class="muted">一台设备、一张活动工单。处理过程留痕，报废保留档案。</p></div></div><AssetTabs />
  <nav class="workspace-tabs" aria-label="运维工作区"><button v-for="(label, key) in tabs" :key="key" class="button" :class="{ primary: tab === key }" :aria-current="tab === key ? 'page' : undefined" @click="switchTab(key)">{{ label }}</button></nav>
  <section class="panel master-list"><form class="list-filters" @submit.prevent="navigate({ ...filters, pageNum: '1', selectedId: undefined })">
    <label>{{ tab === 'devices' ? '编号 / SN关键词' : '设备关键词' }}<input v-model="filters.keyword" aria-label="运维关键词" maxlength="100" /></label>
    <template v-if="tab === 'devices'"><label>设备类型<select v-model="filters.type" aria-label="设备类型"><option value="">全部</option><option v-for="(name, key) in DEVICE_TYPES" :key="key" :value="key">{{ name }}</option></select></label><label>生命周期<select v-model="filters.lifecycle" aria-label="生命周期"><option value="">全部</option><option v-for="(name, key) in DEVICE_FILTERS.lifecycle" :key="key" :value="key">{{ name }}</option></select></label><label>区域<select v-model="filters.areaId" aria-label="运维区域"><option value="">全部</option><option v-for="a in options.data.value?.areas || []" :key="a.id" :value="a.id">{{ a.name }}</option></select></label></template>
    <template v-if="tab === 'orders'"><label>工单状态<select v-model="filters.status" aria-label="工单状态"><option value="">全部</option><option value="OPEN">活动</option><option value="CLOSED">关闭</option></select></label><label>处理阶段<select v-model="filters.phase" aria-label="处理阶段"><option value="">全部</option><option v-for="(name, key) in PHASES" :key="key" :value="key">{{ name }}</option></select></label><label class="inline-check"><input v-model="mine" type="checkbox" />我负责的</label></template>
    <label v-if="tab === 'history'">动作<select v-model="filters.action" aria-label="生命周期动作"><option value="">全部</option><option v-for="key in lifeActions" :key="key" :value="key">{{ RECORD_ACTIONS[key] }}</option></select></label>
    <button class="button primary">查询</button><button type="button" class="button" @click="switchTab(tab)">清除筛选</button></form>
    <p v-if="query.deviceId" class="notice">限定设备：{{ query.deviceId }}</p><p v-if="options.error.value" class="error">区域选项读取失败：{{ options.error.value.message }}</p>
    <QueryState :data="list.data.value" :loading="list.loading.value" :error="list.error.value" @retry="load"><template v-if="list.data.value?.rows"><div class="device-table-wrap"><table class="device-table"><caption class="sr-only">{{ tabs[tab] }}，仅本地数据</caption><thead><tr><th>设备 / 记录</th><th>{{ tab === 'devices' ? '类型 / 区域' : tab === 'orders' ? '来源 / 处理人' : '办理内容' }}</th><th>状态</th><th>{{ tab === 'devices' ? '关系及提醒' : '时间（UTC）' }}</th><th>操作</th></tr></thead><tbody>
      <tr v-for="r in list.data.value.rows" :key="r.id" :class="{ 'selected-row': query.selectedId === r.id }"><td><strong>{{ tab === 'devices' ? r.code : r.deviceCode }}</strong><small>{{ tab === 'devices' ? r.name : r.deviceName }}</small><small v-if="tab === 'orders'">{{ r.id }}</small></td><td><template v-if="tab === 'devices'">{{ DEVICE_TYPES[r.type] }}<small>{{ r.areaName }}</small></template><template v-else-if="tab === 'orders'">{{ r.source === 'MOCK_RETURN' ? '损坏归还' : r.source === 'MOCK_STOCK' ? '库存送修' : '初始工单（来源待补充）' }}<small>{{ r.currentHandlerName || '待指派' }}</small></template><template v-else>{{ r.description || r.inspection || '来源未提供说明' }}<small>经办人 {{ r.actorName || '未知' }}</small></template></td><td>{{ tab === 'devices' ? DEVICE_FILTERS.lifecycle[r.lifecycle] : tab === 'orders' ? PHASES[r.phase] : RECORD_ACTIONS[r.action] }}<small v-if="r.outcome">{{ r.outcome === 'REPAIRED' ? '维修通过' : '无法修复并报废' }}</small></td><td v-if="tab === 'devices'">{{ DEVICE_FILTERS.relation[r.relation] }}<small>{{ DEVICE_FILTERS.communication[r.communication] }}</small></td><td v-else>{{ (tab === 'orders' ? r.createdAt : r.occurredAt) || '未知（不补造时间）' }}</td><td><template v-if="tab === 'devices'"><MaintenanceEntry :device-id="r.id" /><router-link v-for="id in r.activeOrderIds" :key="id" class="button" :to="orderLink(id)">活动维修单</router-link><router-link class="button" :to="deviceLink(r.id)">设备档案</router-link></template><router-link v-else-if="tab === 'orders'" class="button" :to="orderLink(r.id)">查看维修单</router-link><router-link v-else class="button" :to="deviceLink(r.deviceId)">设备档案</router-link></td></tr>
    </tbody></table></div><p v-if="!list.data.value.rows.length" class="query-state">当前筛选下暂无{{ tabs[tab] }}。</p><div class="pagination"><span>共 {{ list.data.value.total }} 条 · 第 {{ pageNum }} 页</span><label>每页<select :value="pageSize" aria-label="运维每页条数" @change="navigate({ pageSize: $event.target.value, pageNum: '1', selectedId: undefined })"><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label><button class="button" :disabled="pageNum <= 1" @click="navigate({ pageNum: String(pageNum - 1), selectedId: undefined })">上一页</button><button class="button" :disabled="pageNum * pageSize >= list.data.value.total" @click="navigate({ pageNum: String(pageNum + 1), selectedId: undefined })">下一页</button></div></template></QueryState>
  </section></section></template>
<script setup>
import { computed, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAdminStore } from '../store'
import { useQuery } from '../useQuery'
import { cleanMaintenanceQuery } from '../navigation'
import { PHASES, RECORD_ACTIONS } from '../maintenanceData'
import { DEVICE_FILTERS, DEVICE_TYPES } from '../deviceData'
import AssetTabs from '../components/AssetTabs.vue'
import QueryState from '../components/QueryState.vue'
import MaintenanceEntry from '../components/MaintenanceEntry.vue'
const route = useRoute(), router = useRouter(), store = useAdminStore(), list = useQuery(), options = useQuery(), filters = reactive({}), mine = ref(false)
const tabs = { devices: '运维设备', orders: '维修工单', history: '生命周期记录' }, lifeActions = ['SEND_REPAIR', 'REPAIRED', 'DISABLED', 'RESTORED', 'SCRAPPED']
const query = computed(() => cleanMaintenanceQuery(route.query)), tab = computed(() => query.value.tab || 'devices'), pageNum = computed(() => Number(query.value.pageNum || 1)), pageSize = computed(() => Number(query.value.pageSize || 20))
function navigate(patch) { router.replace({ path: '/admin/assets/maintenance', query: cleanMaintenanceQuery({ ...query.value, ...patch, mine: mine.value ? 'true' : undefined, siteId: store.siteId }) }) }
function switchTab(value) { router.replace({ path: '/admin/assets/maintenance', query: { siteId: store.siteId, tab: value } }) }
const returnTo = id => '/admin/assets/maintenance?' + new URLSearchParams({ ...query.value, siteId: store.siteId, selectedId: id })
const orderLink = id => ({ path: '/admin/assets/maintenance/' + id, query: { siteId: store.siteId, returnTo: returnTo(id) } })
const deviceLink = id => ({ path: '/admin/assets/devices/' + id, query: { siteId: store.siteId, returnTo: returnTo(id) } })
async function load() { await list.run(tab.value === 'devices' ? 'devices' : tab.value === 'orders' ? 'maintenanceOrders' : 'deviceLifecycleHistory', { ...query.value, siteId: store.siteId, mine: query.value.mine === 'true', pageNum: pageNum.value, pageSize: pageSize.value }); if (list.data.value?.total != null && pageNum.value > Math.max(1, Math.ceil(list.data.value.total / pageSize.value))) navigate({ pageNum: String(Math.max(1, Math.ceil(list.data.value.total / pageSize.value))) }) }
watch(() => [route.fullPath, store.siteId, store.revision], () => { for (const k of ['keyword', 'type', 'lifecycle', 'areaId', 'status', 'phase', 'action']) filters[k] = query.value[k] || ''; mine.value = query.value.mine === 'true'; load(); if (tab.value === 'devices') options.run('deviceOptions', { siteId: store.siteId }) }, { immediate: true })
</script>
