<template><section><div class="page-heading"><div><span class="eyebrow">装备资产 / 运维办理</span><h1>维修与退役</h1><p class="muted">一台设备、一张活动工单。处理过程留痕，报废保留档案。</p></div></div><AssetTabs />
  <nav class="workspace-tabs" aria-label="维修管理"><button v-for="(label, key) in tabs" :key="key" class="button" :class="{ primary: tab === key }" :aria-current="tab === key ? 'page' : undefined" @click="switchTab(key)">{{ label }}</button></nav>
  <section class="panel master-list"><form class="list-filters" @submit.prevent="navigate({ ...filters, pageNum: '1', selectedId: undefined })">
    <label>{{ tab === 'devices' ? '编号 / SN关键词' : '设备关键词' }}<input v-model="filters.keyword" aria-label="运维关键词" maxlength="100" /></label>
    <template v-if="tab === 'devices'"><label>设备类型<select v-model="filters.type" aria-label="设备类型"><option value="">全部</option><option v-for="(name, key) in DEVICE_TYPES" :key="key" :value="key">{{ name }}</option></select></label><label>设备使用状态<select v-model="filters.lifecycle" aria-label="设备使用状态"><option value="">全部</option><option v-for="(name, key) in DEVICE_FILTERS.lifecycle" :key="key" :value="key">{{ name }}</option></select></label><label>区域<select v-model="filters.areaId" aria-label="运维区域"><option value="">全部</option><option v-for="a in options.data.value?.areas || []" :key="a.id" :value="a.id">{{ a.name }}</option></select></label></template>
    <template v-if="tab === 'orders'"><label>工单状态<select v-model="filters.status" aria-label="工单状态"><option value="">全部</option><option value="OPEN">活动</option><option value="CLOSED">关闭</option></select></label><label>处理阶段<select v-model="filters.phase" aria-label="处理阶段"><option value="">全部</option><option v-for="(name, key) in PHASES" :key="key" :value="key">{{ name }}</option></select></label><label class="inline-check"><input v-model="mine" type="checkbox" />我负责的</label></template>
    <label v-if="tab === 'history'">动作<select v-model="filters.action" aria-label="设备使用状态动作"><option value="">全部</option><option v-for="key in lifeActions" :key="key" :value="key">{{ RECORD_ACTIONS[key] }}</option></select></label>
    <div class="filter-actions"><button class="button primary">查询</button><button type="button" class="button" @click="switchTab(tab)">重置</button></div></form>
    <p v-if="query.deviceId" class="notice">限定设备：{{ query.deviceId }}</p><p v-if="options.error.value" class="error">区域选项读取失败：{{ options.error.value.message }}</p>
    <QueryState :data="list.data.value" :loading="list.loading.value" :error="list.error.value" @retry="load"><template v-if="list.data.value?.rows"><div class="device-table-wrap"><table v-table class="admin-table device-table"><caption class="sr-only">{{ tabs[tab] }}，仅本地数据</caption><thead><tr><th data-width="160" class="pinned-key">设备编号</th><th data-width="180">设备名称</th><template v-if="tab === 'devices'"><th data-width="120">类型</th><th data-width="160">区域</th><th data-width="120" class="status-cell">使用状态</th><th data-width="140" class="status-cell">领用关系</th><th data-width="140" class="status-cell">通信状态</th></template><template v-else-if="tab === 'orders'"><th data-width="240">工单编号</th><th data-width="200">来源</th><th data-width="160">处理人</th><th data-width="120" class="status-cell">处理阶段</th><th data-width="180">处理结果</th><th data-width="210">创建时间（UTC）</th></template><template v-else><th data-width="280">办理内容</th><th data-width="160">经办人</th><th data-width="140">动作</th><th data-width="180">处理结果</th><th data-width="210">发生时间（UTC）</th></template><th data-width="240" class="table-actions pinned-actions">操作</th></tr></thead>
<tbody><tr v-for="r in list.data.value.rows" :key="r.id" :class="{ 'selected-row': query.selectedId === r.id }"><td class="pinned-key">{{ tab === 'devices' ? r.code : r.deviceCode }}</td><td>{{ tab === 'devices' ? r.name : r.deviceName }}</td><template v-if="tab === 'devices'"><td>{{ DEVICE_TYPES[r.type] }}</td><td>{{ r.areaName }}</td><td class="status-cell"><span class="badge">{{ DEVICE_FILTERS.lifecycle[r.lifecycle] }}</span></td><td class="status-cell"><span class="badge">{{ DEVICE_FILTERS.relation[r.relation] }}</span></td><td class="status-cell"><span class="badge">{{ DEVICE_FILTERS.communication[r.communication] }}</span></td></template><template v-else-if="tab === 'orders'"><td>{{ r.id }}</td><td>{{ r.source === 'MOCK_RETURN' ? '损坏归还' : r.source === 'MOCK_STOCK' ? '库存送修' : '初始工单（来源待补充）' }}</td><td>{{ r.currentHandlerName || '待指派' }}</td><td class="status-cell"><span class="badge">{{ PHASES[r.phase] }}</span></td><td>{{ !r.outcome ? '—' : r.outcome === 'REPAIRED' ? '维修通过' : '无法修复并报废' }}</td><td>{{ utcTime(r.createdAt) }}</td></template><template v-else><td>{{ r.description || r.inspection || '来源未提供说明' }}</td><td>{{ r.actorName || '未知' }}</td><td>{{ RECORD_ACTIONS[r.action] }}</td><td>{{ !r.outcome ? '—' : r.outcome === 'REPAIRED' ? '维修通过' : '无法修复并报废' }}</td><td>{{ utcTime(r.occurredAt) }}</td></template><td class="table-actions pinned-actions"><div class="row-actions"><template v-if="tab === 'devices'"><MaintenanceEntry :device-id="r.id" /><RowMore><router-link v-for="id in r.activeOrderIds" :key="id" class="button" :to="orderLink(id)">未完成维修单</router-link><router-link class="button" :to="deviceLink(r.id)">设备档案</router-link></RowMore></template><router-link v-else-if="tab === 'orders'" class="button" :to="orderLink(r.id)">查看维修单</router-link><router-link v-else class="button" :to="deviceLink(r.deviceId)">设备档案</router-link></div></td></tr></tbody></table></div><p v-if="!list.data.value.rows.length" class="query-state">当前筛选下暂无{{ tabs[tab] }}。</p><div class="pagination"><span>共 {{ list.data.value.total }} 条 · 第 {{ pageNum }} 页</span><label>每页<select :value="pageSize" aria-label="运维每页条数" @change="navigate({ pageSize: $event.target.value, pageNum: '1', selectedId: undefined })"><option value="20">20</option><option value="50">50</option><option value="100">100</option></select></label><button class="button" :disabled="pageNum <= 1" @click="navigate({ pageNum: String(pageNum - 1), selectedId: undefined })">上一页</button><button class="button" :disabled="pageNum * pageSize >= list.data.value.total" @click="navigate({ pageNum: String(pageNum + 1), selectedId: undefined })">下一页</button></div></template></QueryState>
  </section></section></template>
<script setup>
import { utcTime } from '../tablePresentation'
import { computed, reactive, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAdminStore } from '../store'
import { useQuery } from '../useQuery'
import { cleanMaintenanceQuery } from '../navigation'
import { PHASES, RECORD_ACTIONS } from '../maintenanceData'
import { DEVICE_FILTERS, DEVICE_TYPES } from '../deviceData'
import AssetTabs from '../components/AssetTabs.vue'
import QueryState from '../components/QueryState.vue'
import MaintenanceEntry from '../components/MaintenanceEntry.vue'
const route = useRoute(), router = useRouter(), store = useAdminStore(), list = useQuery(), options = useQuery(), filters = reactive({}), mine = ref(false)
const tabs = { devices: '运维设备', orders: '维修工单', history: '设备使用状态记录' }, lifeActions = ['SEND_REPAIR', 'REPAIRED', 'DISABLED', 'RESTORED', 'SCRAPPED']
const query = computed(() => cleanMaintenanceQuery(route.query)), tab = computed(() => query.value.tab || 'devices'), pageNum = computed(() => Number(query.value.pageNum || 1)), pageSize = computed(() => Number(query.value.pageSize || 20))
function navigate(patch) { router.replace({ path: '/admin/assets/maintenance', query: cleanMaintenanceQuery({ ...query.value, ...patch, mine: mine.value ? 'true' : undefined, siteId: store.siteId }) }) }
function switchTab(value) { router.replace({ path: '/admin/assets/maintenance', query: { siteId: store.siteId, tab: value } }) }
const returnTo = id => '/admin/assets/maintenance?' + new URLSearchParams({ ...query.value, siteId: store.siteId, selectedId: id })
const orderLink = id => ({ path: '/admin/assets/maintenance/' + id, query: { siteId: store.siteId, returnTo: returnTo(id) } })
const deviceLink = id => ({ path: '/admin/assets/devices/' + id, query: { siteId: store.siteId, returnTo: returnTo(id) } })
async function load() { await list.run(tab.value === 'devices' ? 'devices' : tab.value === 'orders' ? 'maintenanceOrders' : 'deviceLifecycleHistory', { ...query.value, siteId: store.siteId, mine: query.value.mine === 'true', pageNum: pageNum.value, pageSize: pageSize.value }); if (list.data.value?.total != null && pageNum.value > Math.max(1, Math.ceil(list.data.value.total / pageSize.value))) navigate({ pageNum: String(Math.max(1, Math.ceil(list.data.value.total / pageSize.value))) }) }
watch(() => [route.fullPath, store.siteId, store.revision], () => { for (const k of ['keyword', 'type', 'lifecycle', 'areaId', 'status', 'phase', 'action']) filters[k] = query.value[k] || ''; mine.value = query.value.mine === 'true'; load(); if (tab.value === 'devices') options.run('deviceOptions', { siteId: store.siteId }) }, { immediate: true })
</script>
