<script setup>
import { computed, reactive, watch } from 'vue'
import EventActions from '@event-actions'
import { enabled as localMode } from '@spatial-actions'
import { useBusinessRevision } from '@/composables/useBusinessRevision'
import { useRoute, useRouter } from 'vue-router'
import { usePortalQuery } from '@/composables/usePortalQuery'
import { useEventWorkspace } from '@/composables/useEventWorkspace'
import { getEvents, getEventSummary } from '@/api/events'
import { eventQuery, eventTimeZone, eventLocalToUtc, eventLocalTime } from '@/utils/event-route'
import { phaseLabels, eventTime } from '@/utils/event-contract'
import WorkspaceState from '@/components/spatial/WorkspaceState.vue'
import DataState from '@/components/personnel/DataState.vue'
import EventFacts from '@/components/events/EventFacts.vue'
import EventReferences from '@/components/events/EventReferences.vue'
import EventScene from '@/components/events/EventScene.vue'
import EventDelivery from '@/components/events/EventDelivery.vue'
const route = useRoute(), router = useRouter(), query = computed(() => eventQuery(route.query)), selectedId = computed(() => query.value.selectedId || '')
const { context, user, siteId, availableSite, detail, reloadDetail } = useEventWorkspace(selectedId)
const list = reactive(usePortalQuery()), summary = reactive(usePortalQuery()), form = reactive({ keyword: '', from: '', to: '', eventType: '', phase: '', error: '' })
const site = computed(() => context.data?.sites.find(s => s.siteId === siteId.value)), zone = computed(() => eventTimeZone(site.value?.timeZone))
const filters = computed(() => ({ siteId: siteId.value, ...Object.fromEntries(Object.entries(query.value).filter(([k]) => ['keyword', 'from', 'to', 'eventType', 'phase', ...(localMode ? ['mine'] : [])].includes(k))) }))
const params = computed(() => ({ ...filters.value, pageNum: Number(query.value.pageNum || 1), pageSize: Number(query.value.pageSize || 20) }))
function select(id) { router.replace({ path: '/alarms', query: { ...query.value, siteId: siteId.value, selectedId: id || undefined } }) }
function page(number) { const q = { ...query.value, siteId: siteId.value, pageNum: String(number) }; delete q.selectedId; router.push({ path: '/alarms', query: q }) }
function search(reset = false) {
  form.error = ''
  try { const q = reset ? { siteId: siteId.value } : { siteId: siteId.value, ...(localMode && query.value.mine ? { mine: 'true' } : {}), keyword: form.keyword, eventType: form.eventType, phase: form.phase, from: eventLocalToUtc(form.from, zone.value), to: eventLocalToUtc(form.to, zone.value) }; if (!reset && (!!q.from !== !!q.to || q.from && Date.parse(q.from) >= Date.parse(q.to))) throw new Error('请填写完整且开始早于结束的时间范围'); router.push({ path: '/alarms', query: eventQuery(q) }) } catch (e) { form.error = e.message }
}
useBusinessRevision(['events'], reload)
watch(() => list.data, result => { if (result?.state === 'AVAILABLE' && Number.isSafeInteger(result.total)) { const last = Math.max(1, Math.ceil(result.total / params.value.pageSize)); if (params.value.pageNum > last) page(last) } })
function reload() { if (!availableSite.value) { list.clear(); summary.clear(); return } list.run(s => getEvents(params.value, s)); summary.run(s => getEventSummary(filters.value, s)) }
watch(() => JSON.stringify([params.value, availableSite.value, user.token]), reload, { immediate: true })
watch(() => JSON.stringify([query.value.keyword, query.value.from, query.value.to, query.value.eventType, query.value.phase, zone.value, siteId.value]), () => { form.keyword = query.value.keyword || ''; form.from = eventLocalTime(query.value.from, zone.value); form.to = eventLocalTime(query.value.to, zone.value); form.eventType = query.value.eventType || ''; form.phase = query.value.phase || ''; form.error = '' }, { immediate: true })
</script>

<template><div class="event-workspace">
  <header class="event-heading"><div><h1>告警与核验</h1><p>{{ localMode ? '事件事实、核验、本地跟进与回执分别表达 · 本地操作' : '设备异常与现场核验协同 · 本阶段只读' }}</p></div><dl class="event-statistics"><div v-for="(label, key) in phaseLabels" :key="key"><dt>{{ label }}</dt><dd>{{ summary.data?.state === 'AVAILABLE' ? summary.data.data.counts[key] : summary.state === 'LOADING' ? '读取中' : summary.error ? '读取失败' : '待接入' }}</dd></div></dl></header>
  <DataState v-if="summary.error" :state="summary.state" :message="summary.error.message" compact retry @retry="summary.run(s => getEventSummary(filters, s))" />
  <DataState v-else-if="summary.data && summary.data.state !== 'AVAILABLE'" :state="summary.data.state" :reason="summary.data.reasonCode" compact />
  <div v-if="localMode" class="s2-actions"><button class="event-button" :aria-pressed="!query.mine" @click="router.push({ path: '/alarms', query: { siteId } })">全部事件</button><button class="event-button" :disabled="user.roles.includes('reader')" :aria-pressed="!!query.mine" @click="router.push({ path: '/alarms', query: { siteId, mine: 'true' } })">我的待办</button><small v-if="user.roles.includes('reader')">只读身份无处置待办</small></div><form class="event-filters" @submit.prevent="search()"><label>设备编号<input v-model="form.keyword" maxlength="100" placeholder="输入设备编号" :disabled="!list.data?.filters.keyword"></label><label>发生时间起<input v-model="form.from" type="datetime-local" step="1" :disabled="!list.data?.filters.timeRange"></label><label>发生时间止<input v-model="form.to" type="datetime-local" step="1" :disabled="!list.data?.filters.timeRange"></label><label>事件类型<select v-model="form.eventType" :disabled="list.data?.filters.eventTypes.state !== 'AVAILABLE'"><option value="">{{ list.data?.filters.eventTypes.state === 'AVAILABLE' ? '全部类型' : '类型来源待接入' }}</option><option v-for="o in list.data?.filters.eventTypes.data || []" :key="o.value" :value="o.value">{{ o.label }}</option></select></label><label>跟进阶段<select v-model="form.phase" :disabled="!list.data?.filters.phase"><option value="">全部阶段</option><option v-for="(label, key) in phaseLabels" :key="key" :value="key">{{ label }}</option></select></label><button class="event-button primary" :disabled="!availableSite">查询</button><button type="button" class="event-button" :disabled="!availableSite" @click="search(true)">重置</button><p class="event-note">时间筛选使用 {{ zone }}{{ !site?.timeZone || site.timeZone !== zone ? '（厂站时区缺失或无效，按 UTC）' : ' 厂站时区' }}；结束时间不包含在区间内。</p><p v-if="form.error" class="event-error" role="alert">{{ form.error }}</p></form>
  <div class="event-list-columns" :class="{ 'has-selection': !!selectedId }"><section class="event-table-panel"><WorkspaceState :context="context" :site-id="siteId" :available-site="availableSite" :query="list" @retry="reload"><div class="event-table-scroll"><table class="event-table"><thead><tr><th>事件编号 / 类型</th><th>关联人员</th><th>设备编号</th><th>发生时间</th><th>跟进阶段</th><th>操作</th></tr></thead><tbody><tr v-for="e in list.data.items" :key="e.eventId" :class="{ selected: selectedId === e.eventId }" @click="select(e.eventId)"><td><button class="event-row-select" :aria-pressed="selectedId === e.eventId" @click.stop="select(e.eventId)">{{ e.eventCode || e.eventId }}</button><strong>{{ e.title }}</strong><small>{{ e.eventType === 'UNKNOWN' ? '类型未知' : list.data.filters.eventTypes.data?.find(o => o.value === e.eventType)?.label || e.eventType }}</small></td><td>{{ e.person.state === 'AVAILABLE' ? e.person.data.map(p => p.name).join('、') || '无关联记录' : e.person.state === 'FORBIDDEN' ? '无权查看' : '归属未知' }}</td><td>{{ e.deviceCode || '未知或无权查看' }}</td><td>{{ eventTime(e.occurredAt) }}</td><td><span class="event-phase" :class="e.phase">{{ phaseLabels[e.phase] }}</span></td><td><router-link class="event-button" @click.stop :to="{ path: '/alarms/' + e.eventId + '/verification', query: { siteId, returnTo: router.resolve({ path: '/alarms', query: { ...query, selectedId: e.eventId } }).fullPath } }">查看核验</router-link><button v-if="!localMode" class="event-button" disabled title="本阶段只读，认领未开放">认领</button></td></tr></tbody></table></div><DataState v-if="!list.data.items.length" state="EMPTY" message="当前筛选范围暂无事件" /><AppPagination :current-page="params.pageNum" :page-size="params.pageSize" :total="list.data.total" @current-change="page" /></WorkspaceState></section>
  <aside v-if="selectedId" class="event-aside"><header><h2>事件摘要</h2><button class="event-button" :disabled="!selectedId" aria-label="关闭事件摘要" @click="select('')">关闭</button></header><DataState v-if="!selectedId" state="IDLE" message="请选择事件查看摘要" /><WorkspaceState v-else :context="context" :site-id="siteId" :available-site="availableSite" :query="detail" @retry="reloadDetail"><template v-if="detail.data"><EventFacts :event="detail.data.event" /><EventActions :event="detail.data.event" :site-id="siteId" /><EventReferences title="关联人员" :section="detail.data.event.person" person-links :site-id="siteId" :return-to="route.fullPath" /><EventReferences title="负责人" :section="detail.data.owner" /><EventReferences title="关联作业摘要" :section="detail.data.works" /><EventScene :detail="detail.data" :site-id="siteId" /><EventDelivery title="摘要回传" :section="detail.data.summaryDelivery" /><EventDelivery title="核验回传" :section="detail.data.verificationDelivery" /><EventDelivery title="原系统状态" :section="detail.data.originalSystem" original /><router-link class="event-button primary" :to="{ path: '/alarms/' + selectedId + '/verification', query: { siteId, returnTo: route.fullPath } }">查看核验详情</router-link><button v-if="!localMode" class="event-button" disabled title="本阶段只读，转交未开放">转交</button></template></WorkspaceState><p class="event-note">{{ localMode ? '点击事件后在摘要操作；核验编辑建议进入详情。所有修改刷新后恢复。' : '认领、转交和现场核验写入尚未开放。' }}</p></aside></div>
</div></template>
