<script setup>
import ContactEntry from '@contact-entry'
import { computed, reactive, ref, watch } from 'vue'
import EventActions from '@event-actions'
import { enabled as localMode } from '@spatial-actions'
import { useRoute } from 'vue-router'
import { useEventWorkspace } from '@/composables/useEventWorkspace'
import { usePortalQuery } from '@/composables/usePortalQuery'
import { getEventRecords } from '@/api/events'
import { personIdPattern } from '@/utils/portal-route'
import { safeEventReturn } from '@/utils/event-route'
import { verificationLabels, conclusionLabels, eventTime } from '@/utils/event-contract'
import WorkspaceState from '@/components/spatial/WorkspaceState.vue'
import DataState from '@/components/personnel/DataState.vue'
import EventFacts from '@/components/events/EventFacts.vue'
import EventReferences from '@/components/events/EventReferences.vue'
import EventScene from '@/components/events/EventScene.vue'
import EventEquipment from '@/components/events/EventEquipment.vue'
import EventEvidence from '@/components/events/EventEvidence.vue'
import EventDelivery from '@/components/events/EventDelivery.vue'
const route = useRoute(), eventId = computed(() => personIdPattern.test(String(route.params.eventId)) ? String(route.params.eventId) : '')
const { context, user, siteId, availableSite, detail, reloadDetail } = useEventWorkspace(eventId)
const timeline = reactive(usePortalQuery()), records = reactive(usePortalQuery()), timelinePage = ref(1), recordPage = ref(1), selectedRecord = ref('')
const currentRecord = computed(() => records.data?.items.find(r => r.id === selectedRecord.value) || records.data?.items[0] || null)
const returnTo = computed(() => safeEventReturn(route.query.returnTo))
function load(kind, number = 1) { const target = kind === 'timeline' ? timeline : records; if (kind === 'timeline') timelinePage.value = number; else { recordPage.value = number; selectedRecord.value = '' } if (!availableSite.value || !eventId.value || !detail.data) return target.clear(); return target.run(s => getEventRecords(eventId.value, kind, { siteId: siteId.value, pageNum: number, pageSize: 5 }, s)) }
watch([siteId, eventId, availableSite, () => user.token, () => detail.data], () => { timelinePage.value = 1; recordPage.value = 1; selectedRecord.value = ''; load('timeline'); load('verifications') }, { immediate: true })
</script>
<template><div class="event-workspace event-verification"><header class="event-heading"><div><h1>事件核验详情</h1><p>告警与核验 / {{ eventId || '事件标识无效' }}</p></div><router-link class="event-button" :to="returnTo">← 返回来源页面</router-link></header><WorkspaceState :context="context" :site-id="siteId" :available-site="availableSite" :query="detail" @retry="reloadDetail"><div v-if="detail.data" class="event-detail-columns"><div class="event-detail-primary"><EventFacts :event="detail.data.event" /><ContactEntry :site-id="siteId" :event-id="eventId" /><EventActions :event="detail.data.event" :site-id="siteId" /><div class="event-associations"><EventReferences title="事件关联人员" :section="detail.data.event.person" person-links :site-id="siteId" :return-to="route.fullPath" /><EventReferences title="负责人" :section="detail.data.owner" /><EventReferences title="关联作业（来源信息只读）" :section="detail.data.works" /></div><div class="event-evidence-columns"><EventScene :detail="detail.data" :site-id="siteId" /><EventEquipment :section="detail.data.equipment" /></div><div class="event-evidence-columns"><section class="event-section"><h3>事实时间线</h3><WorkspaceState :context="context" :site-id="siteId" :available-site="availableSite" :query="timeline" @retry="load('timeline', timelinePage)"><ol class="event-timeline"><li v-for="t in timeline.data.items" :key="t.id"><strong>{{ t.title }}</strong><small>{{ eventTime(t.sourceTime) }}</small><small>来源记录：{{ t.id }}</small></li></ol><DataState v-if="!timeline.data.items.length" state="EMPTY" compact /><AppPagination :current-page="timelinePage" :page-size="5" :total="timeline.data.total" @current-change="load('timeline', $event)" /></WorkspaceState></section><section class="event-section"><h3>相关资料</h3><EventEvidence :section="detail.data.materials" :site-id="siteId" /></section></div></div>
  <aside class="event-detail-secondary"><section class="event-section event-verification-form"><h2>核验记录（只读）</h2><p class="event-caution">{{ localMode ? '此处展示历史记录，只读；编辑请使用左侧“编写核验 / 我的草稿”。' : '本阶段尚未开放保存与提交，不创建本地草稿。' }}</p><WorkspaceState :context="context" :site-id="siteId" :available-site="availableSite" :query="records" @retry="load('verifications', recordPage)"><label v-if="records.data.items.length">已有记录<select v-model="selectedRecord"><option value="">本页第一条记录</option><option v-for="r in records.data.items" :key="r.id" :value="r.id">{{ r.id }} · {{ verificationLabels[r.state] }}</option></select></label><DataState v-else state="EMPTY" message="暂无核验记录" compact /><p v-if="currentRecord" class="event-note">{{ verificationLabels[currentRecord.state] }} · 版本 {{ currentRecord.version || '未知' }} · 提交：{{ eventTime(currentRecord.submittedAt) }}</p><AppPagination :current-page="recordPage" :page-size="5" :total="records.data.total" @current-change="load('verifications', $event)" /></WorkspaceState><label>核验结论<input readonly :value="currentRecord ? conclusionLabels[currentRecord.conclusion] || currentRecord.conclusion || '结论未知' : ''" placeholder="尚无可读取的核验结论"></label><label>现场情况<textarea readonly rows="4" :value="currentRecord?.scene || ''" placeholder="尚无可读取的现场情况"></textarea></label><label>后续措施<textarea readonly rows="3" :value="currentRecord?.measures || ''" placeholder="尚无可读取的后续措施"></textarea></label><p v-if="currentRecord?.conclusion === 'UNCONFIRMED'" class="event-caution">无法确认不等于完成跟进，跟进阶段以事件来源为准。</p><h3>核验证据</h3><EventEvidence v-if="currentRecord" :section="currentRecord.evidence" :site-id="siteId" /><DataState v-else state="NOT_INTEGRATED" message="尚无可读取的核验证据" compact /><div v-if="!localMode" class="event-disabled-actions"><button class="event-button" disabled title="本阶段只读，证据上传未开放">添加现场照片</button><button class="event-button" disabled title="本阶段只读，证据选择未开放">选择证据</button><button class="event-button" disabled title="本阶段只读，草稿保存未开放">保存草稿</button><button class="event-button primary" disabled title="本阶段只读，正式提交未开放">提交核验记录</button></div></section><EventDelivery title="摘要回传" :section="detail.data.summaryDelivery" /><EventDelivery title="核验回传" :section="detail.data.verificationDelivery" /><EventDelivery title="原安监系统（只读）" :section="detail.data.originalSystem" original /></aside></div></WorkspaceState></div></template>
