import { beforeEach, describe, expect, it } from 'vitest'
import { createAdminService } from './service'
import { createSeed } from './seed'
import { maintenanceManager } from './maintenanceData'
import { cleanMaintenanceQuery, maintenanceReturn, safeTarget } from './navigation'
let service, seq
const siteId = 'site-1', deviceId = '19007199254740993012'
function setup(change = () => {}, delay = 0) { const map = new Map(); service = createAdminService({ storage: { getItem: k => map.get(k), setItem: (k, v) => map.set(k, v), removeItem: k => map.delete(k) }, delay, seed: () => { const s = createSeed(); change(s); return s }, now: () => '2026-09-20T12:00:00Z' }); service.login('demo-system', 'Admin@2026') }
beforeEach(() => { seq = 0; setup() })
const q = async (kind, input = {}) => (await service.query(kind, { siteId, ...input })).data
async function command(type, extra = {}) { const d = await q('device', { id: extra.deviceId || deviceId }), o = extra.id ? await q('maintenanceOrder', { id: extra.id }) : null; return { siteId, operationId: `op-${++seq}`, deviceId: d.id, deviceVersion: d.version, ...(o ? { id: o.id, orderVersion: o.version } : {}), ...extra } }
async function run(type, extra = {}) { return (await service.execute(type, await command(type, extra))).data }
const send = (extra = {}) => run('maintenance.create', { reason: '预置外壳检测', handlerId: 'demo-system', handlerVersion: 1, ...extra })
const counts = async () => (await q('overview')).counts
const records = id => q('maintenanceRecords', { id })
describe('A4 maintenance and lifecycle transactions', () => {
  it('keeps baseline and unknown seed facts', async () => { expect(await counts()).toMatchObject({ assets: 36, available: 17, assigned: 12, maintenance: 3 }); const o = (await q('maintenanceOrders')).rows[0]; expect(o.phase).toBe('UNASSIGNED'); expect(o.createdAt).toBeUndefined(); expect((await records(o.id)).total).toBe(0) })
  it('failed inspection appends, passed inspection closes atomically and enables A3 reissue', async () => {
    const before = await q('device', { id: deviceId }), h = await q('assignmentHistory'), r = await send()
    expect(await counts()).toMatchObject({ available: 16, maintenance: 4 })
    await run('maintenance.start', { id: r.orderId })
    await run('maintenance.inspect', { id: r.orderId, result: 'FAIL', repairContent: '预置检修一次', inspection: '预置检测未通过' })
    expect(await q('maintenanceOrder', { id: r.orderId })).toMatchObject({ status: 'OPEN', phase: 'PROCESSING' })
    await run('maintenance.inspect', { id: r.orderId, result: 'PASS', repairContent: '预置再次检修', inspection: '预置检测通过', acknowledged: true })
    expect(await q('maintenanceOrder', { id: r.orderId })).toMatchObject({ status: 'CLOSED', outcome: 'REPAIRED' })
    expect((await records(r.orderId)).rows.map(r => r.action)).toEqual(['PASSED', 'FAILED', 'STARTED', 'CREATED'])
    expect(await counts()).toMatchObject({ available: 17, maintenance: 3 })
    const d = await q('device', { id: deviceId }); expect(d).toMatchObject({ communication: before.communication, sourceTime: before.sourceTime, verification: before.verification })
    expect((await q('assignmentHistory')).total).toBe(h.total)
    await service.execute('assignments.issue', { siteId, operationId: 'after-repair', personId: 'person-1-4', personVersion: 1, acknowledged: true, items: [{ deviceId, deviceVersion: d.version }] })
    expect((await counts()).assigned).toBe(13)
  })
  it('A3 damaged return reuses one order and preserves unknown issuance time', async () => {
    const id = '19007199254740993000', a = (await q('assignments', { deviceId: id })).rows[0]
    const result = (await service.execute('assignments.return', { siteId, operationId: 'damaged', personId: a.personId, personVersion: a.personVersion, acknowledged: true, items: [{ deviceId: id, deviceVersion: a.deviceVersion, assignmentId: a.id, assignmentVersion: a.version, condition: 'REPAIR', reason: '预置损坏', handlerId: 'demo-system', handlerVersion: 1 }] })).data
    const orderId = result.maintenanceOrderIds[0]; expect((await q('maintenanceOrders', { deviceId: id })).total).toBe(1); expect((await records(orderId)).rows[0].action).toBe('RETURN_REPAIR')
    expect(result.history[0].startedAt).toBeNull(); await run('maintenance.start', { deviceId: id, id: orderId })
  })
  it('disable and confirmed restore update only lifecycle and availability', async () => { await run('devices.disable', { reason: '预置停用' }); expect((await counts()).available).toBe(16); await run('devices.restore', { reason: '预置恢复', inspection: '预置检查通过', acknowledged: true }); expect((await counts()).available).toBe(17); expect((await q('deviceLifecycleHistory', { deviceId })).rows.map(r => r.action)).toEqual(['RESTORED', 'DISABLED']) })
  it.each(['devices.scrap', 'maintenance.scrap'])('%s preserves asset total and permanently refuses restoration', async type => {
    const r = type === 'maintenance.scrap' ? await send() : null, d = await q('device', { id: deviceId })
    await run(type, { ...(r ? { id: r.orderId, inspection: '预置无法修复' } : {}), reason: '预置退役', codeConfirmation: d.code, secondConfirmed: true })
    expect(await counts()).toMatchObject({ assets: 36, maintenance: 3, available: 16 })
    if (r) expect(await q('maintenanceOrder', { id: r.orderId })).toMatchObject({ status: 'CLOSED', outcome: 'UNREPAIRABLE_SCRAPPED' })
    await expect(run('devices.restore', { reason: '尝试恢复', inspection: '检查', acknowledged: true })).rejects.toMatchObject({ code: 409 })
    expect((await q('device', { id: deviceId })).writable).toBe(false)
  })
  it.each(['UNKNOWN', 'CONFLICT', 'IN_USE', 'MAINTENANCE', 'SCRAPPED'])('blocks unsafe lifecycle/relationship %s', async value => { setup(s => { const d = s.devices.find(d => d.id === deviceId); if (['UNKNOWN', 'CONFLICT'].includes(value)) d.relation = value; else d.lifecycle = value }); await expect(send()).rejects.toMatchObject({ code: 409 }); expect((await q('deviceLifecycleHistory')).total).toBe(0) })
  it('rejects duplicate orders and inconsistent repair state', async () => { setup(s => { const d = s.devices.find(d => d.id === deviceId); d.lifecycle = 'MAINTENANCE'; for (const id of ['bad1', 'bad2']) s.maintenanceOrders.push({ id, deviceId, siteId, status: 'OPEN', handlerId: 'demo-system', version: 1 }) }); await expect(run('maintenance.start', { id: 'bad1' })).rejects.toMatchObject({ code: 409 }); expect((await records('bad1')).total).toBe(0) })
  it('only handler starts/inspects, admin must explicitly reassign', async () => { const r = await send({ handlerId: 'demo-asset' }); await expect(run('maintenance.start', { id: r.orderId })).rejects.toMatchObject({ code: 403 }); await run('maintenance.assign', { id: r.orderId, handlerId: 'demo-system', handlerVersion: 1, reason: '管理员接管' }); await run('maintenance.start', { id: r.orderId }); expect((await records(r.orderId)).rows[1]).toMatchObject({ oldHandlerName: '资产管理员', handlerName: '系统管理员' }) })
  it('asset handler can repair but cannot scrap or reassign', async () => { const r = await send({ handlerId: 'demo-asset' }); service.login('demo-asset', 'Admin@2026'); await run('maintenance.start', { id: r.orderId }); await expect(run('maintenance.scrap', { id: r.orderId })).rejects.toMatchObject({ code: 403 }); await expect(run('maintenance.assign', { id: r.orderId })).rejects.toMatchObject({ code: 403 }); await run('maintenance.inspect', { id: r.orderId, result: 'FAIL', repairContent: '本地', inspection: '未通过' }) })
  it('administrator role scope cannot borrow ordinary asset scope or a similar role name', () => { const s = createSeed(), a = s.accounts.find(a => a.id === 'demo-site'), d = s.devices.find(d => d.siteId === 'site-2'); s.roles.push({ id: 'fake', name: '厂站管理员', enabled: true, grants: [{ operations: ['assets:read', 'assets:write'], siteIds: ['site-2'], areaIds: '*' }] }); a.roleIds.push('fake'); expect(maintenanceManager(s, a, d)).toBe(false) })
  it.each(['disabled', 'revoked'])('invalid handler %s cannot receive order', async mode => { setup(s => { const a = s.accounts.find(a => a.id === 'demo-asset'); if (mode === 'disabled') a.enabled = false; else a.roleIds = [] }); await expect(send({ handlerId: 'demo-asset' })).rejects.toMatchObject({ code: 409 }); expect((await counts()).maintenance).toBe(3) })
  it('idempotency repeats without duplicate records but different input conflicts', async () => { const input = await command('devices.disable', { reason: '预置停用' }), first = await service.execute('devices.disable', input); expect(await service.execute('devices.disable', input)).toEqual(first); await expect(service.execute('devices.disable', { ...input, reason: '另一个原因' })).rejects.toMatchObject({ code: 409 }); expect((await q('deviceLifecycleHistory')).total).toBe(1) })
  it('old version fails without orders, lifecycle records or audit', async () => { const input = await command('maintenance.create', { reason: '本地', handlerId: 'demo-system', handlerVersion: 1, deviceVersion: 99 }); await expect(service.execute('maintenance.create', input)).rejects.toMatchObject({ code: 409 }); expect((await q('deviceLifecycleHistory')).total).toBe(0); expect((await q('audit')).total).toBe(0) })
  it.each(['reason', 'handlerVersion', 'code', 'second', 'ack', 'forged'])('invalid %s is atomic', async mode => {
    let type = 'maintenance.create', extra = { reason: '预置', handlerId: 'demo-system', handlerVersion: 1 }
    if (mode === 'reason') extra.reason = ''
    if (mode === 'handlerVersion') extra.handlerVersion = 99
    if (['code', 'second'].includes(mode)) { type = 'devices.scrap'; extra = { reason: '报废', codeConfirmation: mode === 'code' ? 'demo-1-013' : 'EQ-1-013', secondConfirmed: mode !== 'second' } }
    if (mode === 'ack') { await run('devices.disable', { reason: '停用' }); type = 'devices.restore'; extra = { reason: '恢复', inspection: '通过' } }
    if (mode === 'forged') extra.lifecycle = 'STOCK'
    const before = await counts(); await expect(run(type, extra)).rejects.toHaveProperty('errorCode'); expect(await counts()).toEqual(before)
  })
  it.each(['abort', 'context', 'identity'])('precommit %s cancels transaction', async mode => { setup(() => {}, 30); const input = await command('devices.disable', { reason: '停用' }), controller = new AbortController(), pending = service.execute('devices.disable', input, { signal: controller.signal }); if (mode === 'abort') controller.abort(); if (mode === 'context') service.changeContext(); if (mode === 'identity') service.login('demo-asset', 'Admin@2026'); await expect(pending).rejects.toBeTruthy(); service.login('demo-system', 'Admin@2026'); expect((await q('deviceLifecycleHistory')).total).toBe(0) })
  it('read-only and anonymous are rejected; object scope and query errors are distinct', async () => { service.login('demo-audit', 'Admin@2026'); await expect(send()).rejects.toMatchObject({ code: 403 }); await expect(q('maintenanceOrder', { id: 'missing' })).rejects.toMatchObject({ code: 404 }); await expect(q('maintenanceOrders', { phase: 'invented' })).rejects.toMatchObject({ code: 400 }); service.logout(); await expect(q('maintenanceOrders')).rejects.toMatchObject({ code: 401 }) })
  it('pagination, scenes and reset remain isolated', async () => { const o = await q('maintenanceOrders', { pageSize: 1, pageNum: 2 }); expect(o.total).toBe(3); expect(o.rows).toHaveLength(1); service.setScenario({ target: 'maintenanceOrders', mode: 'unavailable' }); expect((await q('maintenanceOrders')).availability).toBe('NOT_CONNECTED'); service.restoreScenario(); await run('devices.disable', { reason: '本地' }); service.reset(); service.login('demo-system', 'Admin@2026'); expect((await counts()).available).toBe(17) })
  it('disabled handler is marked invalid until administrator reassigns without rewriting prior facts', async () => {
    const r = await send({ handlerId: 'demo-asset' }); service.login('demo-asset', 'Admin@2026'); await run('maintenance.start', { id: r.orderId }); service.login('demo-system', 'Admin@2026')
    await service.execute('accounts.status', { siteId, operationId: 'disable-handler', id: 'demo-asset', expectedVersion: 1, enabled: false })
    expect(await q('maintenanceOrder', { id: r.orderId })).toMatchObject({ handlerValid: false, phase: 'PROCESSING' })
    expect(() => service.login('demo-asset', 'Admin@2026')).toThrow(); await expect(run('maintenance.inspect', { id: r.orderId })).rejects.toMatchObject({ code: 403 })
    await run('maintenance.assign', { id: r.orderId, handlerId: 'demo-system', handlerVersion: 1, reason: '原处理人停用后接管' }); await run('maintenance.start', { id: r.orderId })
    expect((await records(r.orderId)).rows.filter(r => r.action === 'STARTED').map(r => r.actorName)).toEqual(['系统管理员', '资产管理员'])
  })
  it('site administrator can assign/scrap only inside its own role scope', async () => { service.login('demo-site', 'Admin@2026'); await run('devices.scrap', { reason: '预置', codeConfirmation: 'EQ-1-013', secondConfirmed: true }); await expect(q('device', { siteId: 'site-2', id: '29007199254740993012' })).rejects.toMatchObject({ code: 403 }) })
  it('region-limited admin cannot combine ordinary write/read scope into management scope', () => { const s = createSeed(), a = s.accounts.find(a => a.id === 'demo-site'), d = s.devices.find(d => d.id === deviceId); a.roleIds.push('asset'); a.roleScopes = { site: { siteIds: ['site-1'], areaIds: ['other-area'] } }; expect(maintenanceManager(s, a, d)).toBe(false) })
  it('reads and direct writes respect region visibility', async () => { setup(s => { s.areas.push({ id: 'elsewhere', siteId, enabled: true }); const d = s.devices.find(d => d.id === deviceId); d.areaId = 'elsewhere'; s.accounts.find(a => a.id === 'demo-asset').roleScopes = { asset: { siteIds: [siteId], areaIds: ['area-1'] } } }); service.login('demo-asset', 'Admin@2026'); await expect(q('device', { id: deviceId })).rejects.toMatchObject({ code: 404 }); await expect(service.execute('devices.disable', { siteId, deviceId, deviceVersion: 1, reason: '越权', operationId: 'denied' })).rejects.toMatchObject({ code: 404 }) })
  it('old order version cannot close device or create successful process entry', async () => { const r = await send(); const input = await command('maintenance.inspect', { id: r.orderId, result: 'PASS', repairContent: '本地', inspection: '通过', acknowledged: true }); await run('maintenance.start', { id: r.orderId }); const d = await q('device', { id: deviceId }); await expect(service.execute('maintenance.inspect', { ...input, deviceVersion: d.version })).rejects.toMatchObject({ code: 409 }); expect((await records(r.orderId)).total).toBe(2); expect((await counts()).maintenance).toBe(4) })
  it('closed inspection idempotency rechecks current permission', async () => { const r = await send({ handlerId: 'demo-asset' }); service.login('demo-asset', 'Admin@2026'); await run('maintenance.start', { id: r.orderId }); const input = await command('maintenance.inspect', { id: r.orderId, result: 'PASS', repairContent: '本地', inspection: '通过', acknowledged: true }); const response = await service.execute('maintenance.inspect', input); expect(await service.execute('maintenance.inspect', input)).toEqual(response); service.login('demo-audit', 'Admin@2026'); await expect(service.execute('maintenance.inspect', input)).rejects.toMatchObject({ code: 403 }) })
  it('many inspections paginate immutable history and filter lifecycle separately', async () => { const r = await send(); await run('maintenance.start', { id: r.orderId }); for (let i = 0; i < 22; i++) await run('maintenance.inspect', { id: r.orderId, result: 'FAIL', repairContent: '预置第' + i + '次', inspection: '未通过' }); const second = await q('maintenanceRecords', { id: r.orderId, pageNum: 2 }); expect(second.total).toBe(24); expect(second.rows).toHaveLength(4); expect(second.rows.at(-1).action).toBe('CREATED'); expect((await q('deviceLifecycleHistory', { action: 'SEND_REPAIR' })).total).toBe(1) })
  it.each(['DISABLED', 'SCRAPPED', 'MAINTENANCE'])('A3 rejects new issue to %s after A4', async lifecycle => { if (lifecycle === 'MAINTENANCE') await send(); else await run(lifecycle === 'DISABLED' ? 'devices.disable' : 'devices.scrap', { reason: '预置', ...(lifecycle === 'SCRAPPED' ? { codeConfirmation: 'EQ-1-013', secondConfirmed: true } : {}) }); const d = await q('device', { id: deviceId }); await expect(service.execute('assignments.issue', { siteId, operationId: 'invalid-issue', personId: 'person-1-4', personVersion: 1, acknowledged: true, items: [{ deviceId, deviceVersion: d.version }] })).rejects.toMatchObject({ code: 409 }); expect((await q('assignmentHistory')).total).toBe(0) })
  it('source failure differs from not connected and empty', async () => { service.setScenario({ target: 'maintenanceOrders', mode: 'failure' }); await expect(q('maintenanceOrders')).rejects.toMatchObject({ code: 503, errorCode: 'SOURCE_FAILURE' }); service.restoreScenario(); expect((await q('maintenanceOrders', { siteId: 'site-empty' })).total).toBe(0) })
  it('safe routes retain supported filters only, including old A3 links', () => { expect(cleanMaintenanceQuery({ tab: 'orders', status: 'OPEN', mine: 'true', pageSize: '999', secret: 'x' })).toEqual({ tab: 'orders', status: 'OPEN', mine: 'true' }); expect(maintenanceReturn('https://evil.example')).toBe('/admin/assets/maintenance'); expect(maintenanceReturn('/admin/assets/assignments?tab=history')).toContain('tab=history'); expect(safeTarget('/admin/assets/maintenance/repair-long-id?returnTo=' + encodeURIComponent('/admin/assets/maintenance?tab=orders&status=CLOSED'))).toContain('returnTo=%2Fadmin%2Fassets%2Fmaintenance%3Ftab%3Dorders%26status%3DCLOSED') })
})
