<script setup>
import DemoScene from '@/components/DemoScene.vue'
import { reactive, watch } from 'vue'
import { useS2Workspace } from '@/composables/useS2Workspace'
import { getMaterials, getMaterial } from '@/api/spatial'
import { spatialLabels } from '@/utils/spatial-contract'
import { formatTime } from '@/utils/portal-contract'
import WorkspaceState from '@/components/spatial/WorkspaceState.vue'
import DevicePicker from '@/components/spatial/DevicePicker.vue'
import AppIcon from '@/components/AppIcon.vue'
import MaterialActions from '@material-actions'
import { enabled as localMode } from '@spatial-actions'
const { context, list, detail, query, selectedId, siteId, availableSite, reload, search, select, page } = useS2Workspace('materials', getMaterials, getMaterial)
const filters = reactive({ deviceId: '', date: '' })
watch(query, q => { filters.deviceId = q.deviceId || ''; filters.date = q.from?.slice(0, 10) || '' }, { immediate: true })
function submit(type = query.value.type) {
  search({ deviceId: filters.deviceId, personId: query.value.personId, type, ...(filters.date ? { from: filters.date + 'T00:00:00.000Z', to: filters.date + 'T23:59:59.999Z' } : {}) })
}
</script>

<template>
  <div class="s2-page"><header class="s2-heading"><div><h1>现场影像资料</h1><p>资料检索与关联信息 · 内存文件与设备元数据分别表达</p></div><el-button v-if="!localMode" disabled title="真实上传服务未开放">上传资料</el-button></header><MaterialActions :site-id="siteId" :item="detail.data" :available="availableSite" /><div class="s2-material-layout" :class="{ 'has-selection': !!selectedId }"><section class="s2-material-main"><form class="s2-filterbar" @submit.prevent="submit()"><DevicePicker v-model="filters.deviceId" :site-id="siteId" :enabled="availableSite" /><label>人员<select disabled><option>{{ query.personId || '人员选择来源待接入' }}</option></select></label><label>关联作业<select disabled><option>作业来源待接入</option></select></label><label>采集日期（UTC）<input v-model="filters.date" type="date" :disabled="!availableSite" /></label><el-button native-type="submit" type="primary" :disabled="!availableSite">查询</el-button><el-button @click="search()">重置</el-button></form>
    <nav class="s2-tabs" aria-label="资料类型"><button v-for="(name, type) in { '': '全部资料', PHOTO: '图片', VIDEO: '视频', AUDIO: '音频' }" :key="type" :class="{ active: (query.type || '') === type }" :aria-current="(query.type || '') === type ? 'page' : undefined" @click="submit(type)">{{ name }}</button></nav>
    <WorkspaceState :context="context" :available-site="availableSite" :site-id="siteId" :query="list" @retry="reload"><div class="s2-material-grid"><button v-for="m in list.data?.items" :key="m.id" class="s2-material-card" :data-media-type="m.type" :class="{ selected: selectedId === m.id }" :aria-pressed="selectedId === m.id" @click="select(m.id)"><div class="s2-media-placeholder"><DemoScene v-if="m.type !== 'AUDIO' && m.source !== 'BROWSER_MEMORY'" :identity="m.id" label="AI 封面示意 · 非该资料原图" /><AppIcon :name="m.type === 'PHOTO' ? 'Picture' : m.type === 'VIDEO' ? 'VideoCamera' : 'Microphone'" :size="40" /><span>{{ m.source === 'BROWSER_MEMORY' ? '内存素材 · 选择后可预览' : spatialLabels[m.type] + '文件未接入' }}</span></div><div class="s2-material-caption"><h2>{{ m.name }}</h2><span class="s2-badge">{{ spatialLabels[m.type] }}</span><p>{{ m.deviceCode || '来源设备未知' }} · {{ m.personName || '历史归属未知' }}</p><small>采集时间：{{ formatTime(m.capturedAt) }}</small></div></button></div><p v-if="!list.data?.items.length" class="s2-note">暂无符合条件的资料</p><footer class="s2-pagination"><AppPagination :current-page="Number(query.pageNum || 1)" :page-size="Number(query.pageSize || 20)" :total="list.data?.total || 0" @current-change="page" /></footer></WorkspaceState>
    </section><aside v-if="selectedId" class="s2-panel s2-detail"><div class="s2-card-title"><h2>资料详情</h2><button v-if="selectedId" class="icon-button" aria-label="关闭资料详情" @click="select('')">×</button></div><WorkspaceState :context="context" :available-site="availableSite" :site-id="siteId" :query="detail" idle="请选择左侧资料" @retry="detail.run(s => getMaterial(selectedId, siteId, s))"><template v-if="detail.data"><div class="s2-media-placeholder"><AppIcon name="Document" :size="40" /><strong>{{ detail.data.source === 'BROWSER_MEMORY' ? '浏览器内存素材' : '仅元数据 · 文件未接入' }}</strong><small>{{ detail.data.source === 'BROWSER_MEMORY' ? '使用上方预览或下载；刷新文件消失' : '设备本地存在不等于平台可访问' }}</small></div><h2 class="s2-detail-name">{{ detail.data.name }}</h2><dl class="s2-details"><dt>资料编号</dt><dd>{{ detail.data.id }}</dd><dt>类型</dt><dd>{{ spatialLabels[detail.data.type] }}</dd><dt>来源</dt><dd>{{ detail.data.source === 'BROWSER_MEMORY' ? '本地导入 · 未上传网络' : detail.data.source || '本地元数据，真实文件未接入' }}</dd><dt>采集设备</dt><dd>{{ detail.data.deviceCode || detail.data.deviceId || '未知' }}</dd><dt>关联人员</dt><dd>{{ detail.data.personName || '历史归属未知' }}</dd><dt>关联作业</dt><dd>{{ detail.data.workId || '归属未确认' }}</dd><dt>关联事件</dt><dd>{{ detail.data.eventId || '归属未确认' }}</dd><dt>采集时间</dt><dd>{{ formatTime(detail.data.capturedAt) }}</dd><dt>接收时间</dt><dd>{{ formatTime(detail.data.receivedAt) }}</dd><dt>生成方式</dt><dd>{{ { MOCK_CAPTURE: '本地视频抓拍', MOCK_RECORD: '本地视频录像' }[detail.data.generationMethod] || '非视频生成 / 未知' }}</dd><dt>本地生成时间</dt><dd>{{ formatTime(detail.data.generatedAt) }}</dd><dt>导入时间</dt><dd>{{ formatTime(detail.data.importedAt) }}</dd><dt>关联依据</dt><dd>{{ detail.data.associationSource === 'MANUAL_MOCK' ? '人工关联，非历史佩戴证据' : detail.data.attribution === 'CONFIRMED' ? '来源证据' : '历史归属未知' }}</dd><dt>核验引用</dt><dd>{{ detail.data.frozen ? '版本已冻结，不可覆盖或删除' : '尚未冻结引用' }}</dd></dl></template></WorkspaceState><div v-if="!localMode" class="s2-actions"><el-button v-for="action in ['查看原图', '播放', '下载', '引用']" :key="action" disabled title="真实文件访问和引用服务暂未开放">{{ action }}</el-button></div></aside></div></div>
</template>
