<template><section><div class="page-heading"><div><span class="eyebrow">装备资产 / 台账办理</span><h1>发放与回收</h1><p class="muted">按人员办理，按件记录。损坏归还同时创建维修单，不会先回到可领库存。</p></div></div><AssetTabs /><section class="panel master-list"><nav class="workspace-tabs" aria-label="领用记录类型"><button v-for="(name, key) in tabs" :key="key" class="button" :class="{ primary: tab === key }" :aria-pressed="tab === key" @click="navigate({ tab: key, pageNum: '1', selectedId: undefined })">{{ name }}</button></nav><form class="list-filters" @submit.prevent="navigate({ ...filters, pageNum: '1', selectedId: undefined })"><label>人员 / 设备关键词<input v-model="filters.keyword" maxlength="100" /></label><label>设备类型<select v-model="filters.type"><option value="">全部类型</option><option v-for="(name, type) in DEVICE_TYPES" :key="type" :value="type">{{ name }}</option></select></label><label v-if="tab !== 'current'">办理号<input v-model="filters.batchId" maxlength="100" /></label><div class="filter-actions"><button class="button primary">查询</button><button type="button" class="button" @click="router.replace({ path: route.path, query: { siteId: store.siteId, tab } })">重置</button></div></form><div class="section-heading"><h2>领用记录</h2><div class="actions"><AssignmentEntry /><AssignmentEntry mode="return" /></div></div>
<QueryState :data="list.data.value" :loading="list.loading.value" :error="list.error.value" @retry="load"><template v-if="list.data.value?.rows"><template v-if="tab === 'current'"><div class="table-scroll"><table v-table class="admin-table "><thead><tr><th data-width="160" class="pinned-key">设备编号</th><th data-width="120">设备类型</th><th data-width="160">当前人员</th><th data-width="140" class="status-cell">领用关系</th><th data-width="210">开始时间（UTC）</th><th data-width="180">记录来源</th><th data-width="260" class="table-actions pinned-actions">操作</th></tr></thead><tbody><tr v-for="r in list.data.value.rows" :key="r.id" :class="{ 'selected-row': query.selectedId === r.id }"><td class="pinned-key"><router-link :to="{ path: '/admin/assets/devices/' + r.deviceId, query: { siteId: store.siteId, returnTo: returnPath(r.id) } }">{{ r.code }}</router-link></td><td>{{ DEVICE_TYPES[r.type] }}</td><td><router-link v-if="r.personId" :to="{ path: '/admin/people/' + r.personId, query: { siteId: store.siteId, returnTo: returnPath(r.id) } }">{{ r.personName }}</router-link><span v-else>未知、冲突或范围不可见</span></td><td class="status-cell"><span class="badge">{{ SLOT_NAMES[r.relation] }}</span></td><td>{{ utcTime(r.startedAt) }}</td><td>{{ r.source === 'MOCK_OPERATION' ? '本页本地办理' : '初始领用记录' }}</td><td class="table-actions pinned-actions"><div class="row-actions"><AssignmentEntry compact mode="return" :device-id="r.deviceId" :disabled="r.relation !== 'ASSIGNED' || !r.writable" :reason="r.relation !== 'ASSIGNED' ? '关系需核实，禁止强制归还' : '需要人员和设备双方范围的办理权限'" /><button class="button" @click="navigate({ tab: 'history', deviceId: r.deviceId, selectedId: r.id, pageNum: '1' })">按设备查历史</button></div></td></tr></tbody></table></div><p v-if="!list.data.value.rows.length" class="query-state">暂无当前领用或待核实关系。</p></template><HistoryTable v-else :rows="list.data.value.rows" :return-to="route.fullPath" /><div class="pagination"><span>共 {{ list.data.value.total }} 条 · 第 {{ pageNum }} 页</span><label>每页<select :value="pageSize" @change="navigate({ pageSize: $event.target.value, pageNum: '1' })"><option>20</option><option>50</option><option>100</option></select></label><button class="button" :disabled="pageNum <= 1" @click="navigate({ pageNum: String(pageNum - 1) })">上一页</button><button class="button" :disabled="pageNum * pageSize >= list.data.value.total" @click="navigate({ pageNum: String(pageNum + 1) })">下一页</button></div></template></QueryState></section></section></template>
<script setup>
import { utcTime } from '../tablePresentation'
import { computed, reactive, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAdminStore } from '../store'
import { useQuery } from '../useQuery'
import { cleanAssignmentQuery } from '../navigation'
import { DEVICE_TYPES } from '../deviceData'
import { SLOT_NAMES } from '../assignmentData'
import AssetTabs from '../components/AssetTabs.vue'
import QueryState from '../components/QueryState.vue'
import AssignmentEntry from '../components/AssignmentEntry.vue'
import HistoryTable from '../components/HistoryTable.vue'
const store = useAdminStore(), route = useRoute(), router = useRouter(), list = useQuery(), filters = reactive({}), tabs = { current: '当前领用', returns: '归还记录', history: '全部历史' }
const query = computed(() => cleanAssignmentQuery(route.query)), tab = computed(() => query.value.tab || 'current'), pageNum = computed(() => Number(query.value.pageNum || 1)), pageSize = computed(() => Number(query.value.pageSize || 20))
function returnPath(id) { return route.path + '?' + new URLSearchParams({ ...query.value, selectedId: id, siteId: store.siteId }) }
function navigate(patch) { router.replace({ path: route.path, query: cleanAssignmentQuery({ ...query.value, ...patch, siteId: store.siteId }) }) }
async function load() { await list.run(tab.value === 'current' ? 'assignments' : 'assignmentHistory', { ...query.value, siteId: store.siteId, pageNum: pageNum.value, pageSize: pageSize.value, action: tab.value === 'returns' ? 'RETURN' : undefined }); if (list.data.value?.total != null) { const last = Math.max(1, Math.ceil(list.data.value.total / pageSize.value)); if (pageNum.value > last) navigate({ pageNum: String(last) }) } }
watch(() => [route.fullPath, store.siteId, store.revision], () => { for (const key of ['keyword', 'type', 'batchId']) filters[key] = query.value[key] || ''; load() }, { immediate: true })
</script>
