async (page) => {
  const origin = page.url().split('/').slice(0, 3).join('/'), checks = [], errors = [], requests = []
  const check = (ok, label) => { if (!ok) throw new Error(label); checks.push(label) }
  page.on('pageerror', e => errors.push(e.message))
  page.on('request', r => { if (/\/(dev-api|demo-api|mock-events)\//.test(r.url())) requests.push(r.url()) })
  const button = name => page.getByRole('button', { name, exact: true })
  await page.goto(origin + '/#/login')
  await page.getByRole('button', { name: /^(用户菜单|登录)$/ }).first().waitFor()
  if (await button('用户菜单').count()) { await button('用户菜单').click(); await page.getByText('退出登录', { exact: true }).click() }
  await page.getByRole('textbox', { name: '账号', exact: true }).fill('admin')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('Admin@2026')
  await button('登录').click(); await button('用户菜单').waitFor()
  await page.goto(origin + '/#/alarms?siteId=mock-site-1')
  await page.reload()
  await page.getByRole('heading', { name: '告警事件', exact: true }).waitFor()
  await page.locator('.event-table tbody tr').first().waitFor()
  check(await button('未处理').getAttribute('aria-pressed') === 'true', '默认未处理')
  check(!/认领事件|转现场核验|编写核验|本地回执/.test(await page.locator('.alarm-workspace').innerText()), '移除旧流程操作')
  for (const [value, label] of [['HELMET', '安全帽'], ['BELT', '安全带'], ['WATCH', '手表']]) {
    await page.getByRole('combobox', { name: '设备类型', exact: true }).selectOption(value)
    await button('查询').click()
    await page.waitForFunction(v => [...document.querySelectorAll('.event-table tbody tr')].length > 0 && [...document.querySelectorAll('.event-table tbody tr')].every(r => r.children[1].textContent === v), label)
    check(true, '筛选' + label)
  }
  await button('重置').click()
  await page.getByLabel('设备编号 / 人员姓名', { exact: true }).fill('EQ-1-3-helmet')
  await button('查询').click()
  await page.waitForFunction(() => document.querySelectorAll('.event-table tbody tr').length === 1)
  check((await page.locator('.event-table tbody').innerText()).includes('脱帽告警'), '设备编号对应脱帽告警')
  await page.setViewportSize({ width: 1440, height: 900 })
  await page.screenshot({ path: 'output/playwright/alarms/list-1440.png', fullPage: true })
  await button('处理').click()
  const dialog = page.getByRole('dialog', { name: '处理告警', exact: true })
  await dialog.waitFor()
  await dialog.getByRole('button', { name: '确认处理', exact: true }).click()
  await dialog.getByRole('alert').waitFor()
  check(true, '空说明拒绝提交')
  await dialog.getByLabel('处理说明', { exact: false }).fill('  已提醒现场人员重新佩戴并检查帽带。  ')
  await dialog.getByRole('button', { name: '取消', exact: true }).click()
  await button('继续编辑').click()
  await page.getByRole('dialog', { name: '放弃未保存内容？', exact: true }).waitFor({ state: 'hidden' })
  check((await dialog.getByLabel('处理说明', { exact: false }).inputValue()).includes('重新佩戴'), '取消离开保留输入')
  await page.screenshot({ path: 'output/playwright/alarms/handle-1440.png', fullPage: true })
  await dialog.getByRole('button', { name: '确认处理', exact: true }).click()
  await dialog.waitFor({ state: 'hidden' })
  await page.getByText('当前筛选范围暂无告警', { exact: true }).waitFor()
  await button('已处理').click()
  await page.locator('.event-table tbody tr').first().waitFor()
  check((await page.locator('.event-table tbody').innerText()).includes('已提醒现场人员重新佩戴并检查帽带。'), '处理后移至已处理且保留说明')
  check(await button('处理').count() === 0, '已处理只读')
  await page.getByRole('link', { name: '查看详情', exact: true }).click()
  await page.getByRole('heading', { name: '告警详情', exact: true }).waitFor()
  await page.getByRole('heading', { name: '处理记录', exact: true }).waitFor()
  check((await page.locator('.alarm-facts').innerText()).includes('已提醒现场人员'), '详情显示完整记录')
  await page.getByRole('link', { name: '← 返回来源页面', exact: true }).click()
  await page.getByRole('heading', { name: '告警事件', exact: true }).waitFor()
  check(await button('已处理').getAttribute('aria-pressed') === 'true', '返回保留筛选和页签')
  await page.goto(origin + '/#/alarms/event-1-3/verification?siteId=mock-site-1&returnTo=%2Foverview%3FsiteId%3Dmock-site-1')
  await page.getByRole('heading', { name: '告警详情', exact: true }).waitFor()
  check(!page.url().includes('/verification'), '旧详情地址重定向')
  await page.getByRole('link', { name: '← 返回来源页面', exact: true }).click()
  await page.getByRole('heading', { name: '安全运行总览', exact: true }).waitFor()
  check(!/待认领|待现场核验/.test(await page.locator('#main-content').innerText()), '总览不再显示旧状态')
  await page.goto(origin + '/#/alarms?siteId=mock-site-1&handlingStatus=HANDLED')
  await page.locator('.event-table tbody tr').first().waitFor()
  await page.setViewportSize({ width: 1280, height: 800 })
  check(!await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), '1280宽度无页面溢出')
  await page.screenshot({ path: 'output/playwright/alarms/handled-1280.png', fullPage: true })
  await button('用户菜单').click()
  await page.getByText('退出登录', { exact: true }).click()
  await page.getByRole('textbox', { name: '账号', exact: true }).fill('viewer')
  await page.getByRole('textbox', { name: '密码', exact: true }).fill('View@2026')
  await button('登录').click()
  await button('用户菜单').waitFor()
  await page.goto(origin + '/#/alarms?siteId=mock-site-1')
  await page.locator('.event-table tbody tr').first().waitFor()
  check(await button('处理').count() > 0 && await button('处理').first().isDisabled(), '只读身份禁止处理')
  await page.getByLabel('当前厂站', { exact: true }).selectOption('mock-site-empty')
  await page.getByText('当前筛选范围暂无告警', { exact: true }).waitFor()
  check(true, '空厂站显示空结果')
  check(errors.length === 0, '无浏览器异常: ' + errors.join(';'))
  check(requests.length === 0, '未请求真实业务或处理接口')
  return { checks, errors, requests }
}
