import test from 'node:test'
import assert from 'node:assert/strict'
import { eventQuery, safeEventReturn, eventTimeZone, eventLocalToUtc, eventLocalTime } from '../src/utils/event-route.js'
import { validateEventFact, validateEventPage, validateEventSummary, validateEventDetail, validateEventRecords, uniqueEventOrigins, eventTime } from '../src/utils/event-contract.js'
import { safeWorkspaceReturn } from '../src/utils/spatial-contract.js'
const missing = () => ({ state: 'NOT_INTEGRATED', data: null, reasonCode: 'SOURCE_NOT_INTEGRATED' })
const fact = (eventId='90071992547409931234') => ({ eventId, siteId:'s', title:'合成事件', sourceSystem:'TEST', sourceEventId:eventId, eventType:'UNKNOWN', phase:'UNKNOWN', freshness:'UNKNOWN', occurredAt:null, receivedAt:null, sourceUpdatedAt:null, person:missing(), legacyHandled:1 })
const page = () => ({ state:'AVAILABLE',items:[fact()],total:1,pageNum:1,pageSize:20,scope:{siteId:'s'},filters:{keyword:true,timeRange:true,phase:true,eventTypes:missing()} })
test('long event IDs preserved; legacy handled does not map to completed',()=>{const f=validateEventFact(fact(),'s');assert.equal(f.eventId,'90071992547409931234');assert.equal(f.phase,'UNKNOWN');assert.equal(f.legacyHandled,1)})
test('unsafe numeric ID rejected',()=>{const f=fact();f.eventId=9007199254740994;assert.throws(()=>validateEventFact(f,'s'))})
test('source identity dedup keeps same number from different systems',()=>{const a=fact('a'),b=fact('b');b.sourceEventId='a';b.sourceSystem='SECOND';assert.equal(uniqueEventOrigins([a,a,b]).length,2);b.sourceSystem='TEST';assert.throws(()=>uniqueEventOrigins([a,b]))})
test('conflicting platform identity rejected',()=>{const a=fact('a'),b={...a,sourceSystem:'OTHER'};assert.throws(()=>uniqueEventOrigins([a,b]))})
test('page scope and pagination checked',()=>{assert.equal(validateEventPage(page(),{siteId:'s'}).total,1);assert.throws(()=>validateEventPage(page(),{siteId:'other'}));assert.throws(()=>validateEventPage(page(),{siteId:'s',pageNum:2}))})
test('missing not zero',()=>{const p=page();p.state='NOT_INTEGRATED';p.reasonCode='EVENT_NOT_INTEGRATED';p.items=[];p.total=null;validateEventPage(p,{siteId:'s'});p.total=0;assert.throws(()=>validateEventPage(p,{siteId:'s'}))})
test('duplicate rows rejected rather than changing total',()=>{const p=page();p.items.push(fact());p.total=2;assert.throws(()=>validateEventPage(p,{siteId:'s'}))})
test('unknown timestamp never epoch or receipt fallback',()=>{assert.equal(eventTime(null),'时间未知');const f=fact();f.receivedAt='2026-09-17T00:00:00Z';assert.equal(validateEventFact(f,'s').occurredAt,null)})
test('freshness needs actual source update',()=>{const f=fact();f.freshness='STALE';assert.throws(()=>validateEventFact(f,'s'));f.sourceUpdatedAt='2026-09-01T00:00:00Z';validateEventFact(f,'s')})
test('statistics complete phase partition',()=>{const s={state:'AVAILABLE',data:{total:2,counts:{UNCLAIMED:0,PROCESSING:0,AWAITING_VERIFICATION:1,LOCAL_COMPLETED:0,UNKNOWN:1},sourceTime:null}};validateEventSummary(s);s.data.counts.UNCLAIMED=1;assert.throws(()=>validateEventSummary(s))})
test('summary missing remains null',()=>assert.equal(validateEventSummary(missing()).data,null))
test('event detail sections require association evidence',()=>{const d={event:fact(),...Object.fromEntries(['owner','equipment','works','location','video','materials','summaryDelivery','verificationDelivery','originalSystem'].map(k=>[k,missing()]))};validateEventDetail(d,'s',fact().eventId);d.owner={state:'AVAILABLE',data:[{id:'p',siteId:'s',name:'x',attribution:'UNKNOWN',snapshotKind:'UNKNOWN'}]};assert.throws(()=>validateEventDetail(d,'s',fact().eventId))})
test('metadata nested URLs prohibited',()=>{const f=fact();f.person.url='https://invalid';assert.throws(()=>validateEventFact(f,'s'))})
test('draft cannot contain submission time',()=>{const p=page();p.scope.eventId='e';p.items=[{id:'v',eventId:'e',siteId:'s',state:'DRAFT',sourceTime:null,submittedAt:null,evidence:missing()}];validateEventRecords(p,{siteId:'s'},'e','verifications');p.items[0].submittedAt='2026-09-01T00:00:00Z';assert.throws(()=>validateEventRecords(p,{siteId:'s'},'e','verifications'))})
test('query whitelist and safe redirects',()=>{assert.deepEqual(eventQuery({siteId:'s',phase:'BAD',selectedId:'../a',url:'x',pageSize:101}),{siteId:'s'});for(const v of ['//evil','https://evil','/video','/alarms#bad','/\\evil'])assert.equal(safeEventReturn(v),'/alarms');assert.equal(safeEventReturn('/alarms?phase=UNKNOWN&url=evil'),'/alarms?phase=UNKNOWN');assert.equal(safeWorkspaceReturn('/alarms?selectedId=e'),'/alarms?selectedId=e')})
test('verification login restoration discards unsafe return',()=>assert.equal(safeEventReturn('/alarms/e/verification?siteId=s&returnTo=https://evil',true),'/alarms/e/verification?siteId=s&returnTo=%2Falarms'))
test('station timezone conversion independent of browser timezone',()=>{assert.equal(eventLocalToUtc('2026-09-17T08:00','Asia/Shanghai'),'2026-09-17T00:00:00.000Z');assert.equal(eventLocalTime('2026-09-17T00:00:00Z','Asia/Shanghai'),'2026-09-17T08:00:00')})
test('missing/invalid station timezone uses explicit UTC',()=>{assert.equal(eventTimeZone(null),'UTC');assert.equal(eventTimeZone('not-zone'),'UTC');assert.equal(eventLocalToUtc('2026-09-17T08:00',null),'2026-09-17T08:00:00.000Z')})
test('DST gaps and folds not guessed',()=>{assert.throws(()=>eventLocalToUtc('2026-03-08T02:30','America/New_York'));assert.throws(()=>eventLocalToUtc('2026-11-01T01:30','America/New_York'));assert.equal(eventLocalToUtc('2026-09-17T08:00','America/New_York'),'2026-09-17T12:00:00.000Z')})
test('invalid calendar dates and reversed route range discarded',()=>{assert.throws(()=>eventLocalToUtc('2026-02-30T10:00','UTC'));assert.equal(eventLocalToUtc('', 'UTC'),null);assert.deepEqual(eventQuery({from:'2026-09-18T00:00:00Z',to:'2026-09-17T00:00:00Z'}),{})})
