import { test } from 'node:test'
import assert from 'node:assert/strict'
import { reliablePosition, positionReason, s2Query, safeWorkspaceReturn, validateS2Page, validateS2Item, validateTrack, trackGeometry, validRing } from '../src/utils/spatial-contract.js'
import { createTrackPlayer } from '../src/utils/track-player.js'
const point = (n = 0) => ({ longitude: n, latitude: n, quality: 'VALID', coordinateSystem: 'WGS84', sourceTime: `2026-09-17T00:0${n}:00Z`, receivedAt: null, freshness: 'UNKNOWN' })
const q = { siteId: 's', deviceId: '900719925474099312', from: '2026-09-17T00:00:00Z', to: '2026-09-17T01:00:00Z' }
const track = () => ({ id: 't', siteId: 's', name: '测试轨迹', ...q, complete: true, attribution: 'UNKNOWN', personId: null, segments: [{ segmentId: 'seg', continuity: 'CONFIRMED', points: [point(0), point(1), point(2)] }], gaps: [] })
test('零坐标有效；字符串、非有限数、范围外不落点', () => { assert.ok(reliablePosition(point())); for (const longitude of [null, '0', NaN, Infinity, 181]) assert.equal(reliablePosition({ ...point(), longitude }), false) })
test('未知及未支持坐标系不转换', () => { for (const coordinateSystem of [null, 'GCJ02', 'BD09']) assert.equal(reliablePosition({ ...point(), coordinateSystem }), false) })
test('质量、源时间、过期独立表达', () => { assert.equal(reliablePosition({ ...point(), quality: 'UNKNOWN' }), false); assert.match(positionReason({ ...point(), freshness: 'STALE' }), /过期/); assert.match(positionReason({ ...point(), sourceTime: null }), /源时间未知/) })
test('长 ID 不转换为数值，参数白名单', () => { assert.equal(s2Query('tracks', { ...q, token: 'x' }).deviceId, q.deviceId); assert.equal(s2Query('tracks', { ...q, token: 'x' }).token, undefined); assert.deepEqual(s2Query('materials', { pageSize: 101, selectedId: '../x' }), {}) })
test('错误时间范围清除，不恢复非法筛选', () => { assert.equal(s2Query('tracks', { ...q, to: q.from }).from, undefined); assert.equal(s2Query('materials', { type: 'HTML', status: 'ENABLED' }).type, undefined) })
test('站内恢复及外部、双斜线、哈希跳转拦截', () => { for (const path of ['//evil.test', 'https://evil.test', '/location#x', '/location/../login', '/location\\evil']) assert.equal(safeWorkspaceReturn(path), '/personnel'); assert.equal(safeWorkspaceReturn('/location?tab=tracks&deviceId=a&token=secret'), '/location?tab=tracks&deviceId=a') })
test('空分页与未接入严格区分', () => { const p = { state: 'AVAILABLE', items: [], total: 0, pageNum: 1, pageSize: 20, scope: { siteId: 's' } }; validateS2Page(p, 'devices', q); assert.throws(() => validateS2Page({ ...p, state: 'NOT_INTEGRATED' }, 'devices', q)); validateS2Page({ ...p, state: 'NOT_INTEGRATED', total: null, reasonCode: 'SOURCE_NOT_INTEGRATED' }, 'devices', q) })
test('分页与站点、重复对象不匹配拒绝', () => { const i = { id: 'a', siteId: 's', name: '测试', type: 'HELMET' }; const p = { state: 'AVAILABLE', items: [i, i], total: 2, pageNum: 1, pageSize: 20, scope: { siteId: 's' } }; assert.throws(() => validateS2Page(p, 'devices', q)); assert.throws(() => validateS2Item(i, 'devices', 'other')) })
test('资料地址字段禁止暴露，历史归属不可猜测', () => { const m = { id: 'm', siteId: 's', name: '合成资料', type: 'PHOTO', capturedAt: null, receivedAt: null }; validateS2Item(m, 'materials', 's'); assert.throws(() => validateS2Item({ ...m, fileUrl: 'private' }, 'materials', 's')); assert.throws(() => validateS2Item({ ...m, personId: 'p', attribution: 'UNKNOWN' }, 'materials', 's')) })
test('有效轨迹契约，错误对象和未声明截断拒绝', () => { validateTrack({ state: 'AVAILABLE', data: track() }, q); assert.throws(() => validateTrack({ state: 'AVAILABLE', data: { ...track(), deviceId: 'other' } }, q)); assert.throws(() => validateTrack({ state: 'AVAILABLE', data: { ...track(), complete: false } }, q)) })
test('未知连续性仅展示离散点', () => { const t = track(); t.segments[0].continuity = 'UNKNOWN'; assert.equal(trackGeometry(t).lines.length, 0); assert.equal(trackGeometry(t).points.length, 3) })
test('无效点打断，不能过滤后跨点连线', () => { const t = track(); t.segments[0].points[1].quality = 'UNKNOWN'; assert.equal(trackGeometry(t).lines.length, 0) })
test('来源明确缺口不连线', () => { const t = track(); t.gaps = [{ from: point(0).sourceTime, to: point(1).sourceTime }]; assert.equal(trackGeometry(t).lines[0].length, 2) })
test('片段之间不连线，无源时间不连接', () => { const t = track(); t.segments.push({ segmentId: 'next', continuity: 'CONFIRMED', points: [point(3)] }); assert.equal(trackGeometry(t).lines.length, 1); t.segments[0].points[1].sourceTime = null; assert.equal(trackGeometry(t).lines.length, 0) })
test('围栏必须闭合、可靠、WGS84', () => { const f = { coordinateSystem: 'WGS84', ring: [[0, 0], [1, 0], [1, 1], [0, 0]] }; assert.ok(validRing(f)); assert.equal(validRing({ ...f, ring: f.ring.slice(0, 3) }), false); assert.equal(validRing({ ...f, coordinateSystem: 'BD09' }), false) })
test('播放仅实际点，暂停停止倍速卸载清理', () => { const pending = new Map(); let seq = 0, current, running; const player = createTrackPlayer((p, i, r) => { current = p; running = r }, (fn, ms) => { pending.set(++seq, { fn, ms }); return seq }, id => pending.delete(id)); const p = [point(0), point(1)]; player.load(p); player.play(); assert.equal(running, true); player.speed(4); assert.equal([...pending.values()][0].ms, 250); [...pending.values()][0].fn(); assert.equal(current, p[1]); player.pause(); assert.equal(running, false); player.stop(); assert.equal(current, p[0]); player.load([]); player.play(); assert.equal(running, false); player.dispose() })
