import test from 'node:test'
import assert from 'node:assert/strict'
import { createVideoPlayer } from '../src/utils/video-player.js'
import { flvAdapter } from '../src/utils/video-adapters.js'
class Events { listeners = new Map(); addEventListener(k, f) { if (!this.listeners.has(k)) this.listeners.set(k, new Set()); this.listeners.get(k).add(f) } removeEventListener(k, f) { this.listeners.get(k)?.delete(f) } emit(k) { for (const f of this.listeners.get(k) || []) f() } count() { return [...this.listeners.values()].reduce((n, s) => n + s.size, 0) } }
function fixture(extra = {}) {
  const media = Object.assign(new Events(), { paused: false, ended: false, readyState: 4, currentTime: 0, removeAttribute() {}, load() {}, pause() {} }), doc = new Events(), timers = new Map()
  let time = 0, releases = 0, destroys = 0, acquisitions = 0
  const provider = { async acquire() { acquisitions++; return { state: 'AVAILABLE', release() { releases++ } } } }
  const p = createVideoPlayer({ media, documentRef: doc, provider, clock: { setInterval(f) { const k = timers.size + 1; timers.set(k, f); return k }, clearInterval(k) { timers.delete(k) } }, now: () => time, createAdapter: () => ({ load() {}, play: async () => {}, destroy() { destroys++ } }), ...extra })
  return { p, media, doc, timers, tick() { time += 6000; for (const f of timers.values()) f() }, counts: () => ({ releases, destroys, acquisitions }) }
}
test('play promise is not playing; advancing frame is', async () => { const f = fixture(); await f.p.start(); assert.equal(f.p.snapshot.state, 'CONNECTING'); f.media.emit('playing'); assert.equal(f.p.snapshot.state, 'CONNECTING'); f.media.currentTime = 1; f.media.emit('timeupdate'); assert.equal(f.p.snapshot.state, 'PLAYING'); assert.equal(f.p.snapshot.sourceTime, null); assert.ok(f.p.snapshot.lastDisplayedAt); f.p.destroy() })

test('looped synthetic media accepts real frames after timeline wraps', async () => { const f = fixture(); f.media.loop = true; await f.p.start(); f.media.emit('playing'); f.media.currentTime = 5.9; f.media.emit('timeupdate'); f.tick(); assert.equal(f.p.snapshot.state, 'INTERRUPTED'); f.media.currentTime = 0.1; f.media.emit('timeupdate'); assert.equal(f.p.snapshot.state, 'PLAYING'); f.p.destroy(); assert.equal(f.media.count(), 0); assert.equal(f.timers.size, 0) })
test('buffering, stalled, ended never report playing', async () => { const f = fixture(); await f.p.start(); f.media.emit('playing'); f.media.emit('timeupdate'); f.media.emit('waiting'); assert.equal(f.p.snapshot.state, 'BUFFERING'); f.media.emit('stalled'); assert.equal(f.p.snapshot.state, 'INTERRUPTED'); f.media.emit('ended'); assert.equal(f.p.snapshot.state, 'INTERRUPTED'); f.p.destroy() })
test('frame watchdog and retry never auto reconnect', async () => { const f = fixture(); await f.p.start(); f.tick(); assert.equal(f.p.snapshot.state, 'INTERRUPTED'); assert.equal(f.counts().acquisitions, 1); await f.p.retry(); assert.equal(f.counts().acquisitions, 2); f.p.destroy() })
test('error releases resources; late events ignored', async () => { const f = fixture(); await f.p.start(); const late = [...f.media.listeners.get('playing')][0]; f.media.emit('error'); assert.equal(f.p.snapshot.state, 'ERROR'); late(); assert.equal(f.p.snapshot.state, 'ERROR'); assert.equal(f.media.count(), 0); assert.equal(f.timers.size, 0); f.p.destroy() })
test('hidden pauses and releases, show does not restart', async () => { const f = fixture(); await f.p.start(); f.doc.hidden = true; f.doc.emit('visibilitychange'); assert.equal(f.p.snapshot.state, 'PAUSED'); f.doc.hidden = false; f.doc.emit('visibilitychange'); assert.equal(f.counts().acquisitions, 1); assert.equal(f.counts().releases, 1); f.p.destroy() })
test('mute/fullscreen rejection and idempotent destroy', async () => { const f = fixture(); await f.p.start(); f.p.mute(false); assert.equal(f.media.muted, false); assert.equal(await f.p.fullscreen(), false); f.p.pause(); f.p.destroy(); f.p.destroy(); assert.equal(f.doc.count(), 0); assert.equal(f.media.count(), 0); assert.equal(f.timers.size, 0); assert.equal(f.counts().releases, 1) })
test('pending provider cannot revive destroyed player', async () => { let resolve, released = 0; const f = fixture({ provider: { acquire: () => new Promise(r => { resolve = r }) } }); const run = f.p.start(); f.p.destroy(); resolve({ state: 'AVAILABLE', release() { released++ } }); await run; assert.equal(released, 1); assert.equal(f.timers.size, 0) })
test('closed production provider never creates adapter', async () => { const f = fixture({ provider: undefined, createAdapter() { throw new Error('must not run') } }); await f.p.start(); assert.equal(f.p.snapshot.state, 'NOT_INTEGRATED'); f.p.destroy() })
test('adapter play error handled without leaking', async () => { const f = fixture({ createAdapter: () => ({ load() {}, async play() { throw new Error() }, destroy() {} }) }); await f.p.start(); assert.equal(f.p.snapshot.state, 'ERROR'); assert.equal(f.timers.size, 0); f.p.destroy() })
test('FLV adapter init, error handler, unload and repeated destroy', async () => { const calls = [], player = Object.fromEntries(['on', 'off', 'attachMediaElement', 'load', 'play', 'pause', 'unload', 'detachMediaElement', 'destroy'].map(k => [k, () => { calls.push(k) }])); const engine = { isSupported: () => true, Events: { ERROR: 'error' }, createPlayer: () => player }; const a = flvAdapter(engine, {}, { url: 'blob:test-only' }, () => {}); a.load(); await a.play(); a.destroy(); a.destroy(); assert.deepEqual(calls, ['on', 'attachMediaElement', 'load', 'play', 'off', 'pause', 'unload', 'detachMediaElement', 'destroy']); assert.throws(() => flvAdapter({ isSupported: () => false }, {}, {}, () => {})) })
